### ISSUE TITLE
Password Crash

### ISSUE THREAD

**Issue by nathanila** [openconnect/openconnect-gui#101]
In order to send a password to openconnect.exe, it is recommended to do the following:

`echo "password" | openconnect.exe" --passwd-on-stdin ...`

However, this causes openconnect.exe to crash.  It complains about the stdin handle being invalid.

**Comment by horar** [comment]
yeap,
- openconnect console client bundled with openconnecct-gui v1.3 (v7.06-unknown) crash with this error:

> GRUP: [ ... | ... | ... | ...]: :  ReadConsole() failed: Incorrect function.

- openconnect console client already build in present (v7.06) stop with this error:

> GRUP: [ ... | ... | ... | ...]: :  ReadConsole() failed: Incorrect function.
> Failed to obtain WebVPN cookie

Anyway, this should be discussed with openconnect console/library client via 
[mailing list](http://www.infradead.org/openconnect/mail.html).

**Comment by dwmw2** [comment]
Does this fix it?

[0001-Attempt-to-re-open-CONIN-if-stdin-has-been-redirecte.patch.txt](https://github.com/openconnect/openconnect-gui/files/489838/0001-Attempt-to-re-open-CONIN-if-stdin-has-been-redirecte.patch.txt)

**Comment by horar** [comment]
hi, I try to build yesterday the openconnect.exe from git (attached patch was included). The result was that after app start it stop (no output to console) and it continue after pressing Enter.
Looks like it was waiting for input?
(win10 home; console with admin rights)

**Comment by dwmw2** [comment]
Right, it's waiting for the password to be provided on stdin. I understand pipelines and redirection are... strange on Windows; was it not behaving like that before the patch? Nothing should have changed there; this should only make it change its behaviour when it needs to interact with the user.

**Comment by horar** [comment]
yes, windows and *nix words differ sometimes too much :/
There is only one difference. The previous version just proceed with connection.... ignore the pwd echo-ed via pipe and continue...
After applying you patch, the openconnect. exe wait for user input but ignore the input from pipe.
I trigger the command in form described bellow and it immediatelly wait for user input. Funny, when I type my password in this stage, it accept/read them and openconnect use them for connection.  When I press enter again without typing, it will ask or password later. 
But expected is to read the password via pipe. I guess we lost somewhere the pipe data and/or 

I'm starting the app in this form:
echo MY_PASSWORD | openconnect.exe -v --user=MY_NAME --passwd-on-stdin --authgroup=MY_GROUP --os=win https://SERVER_NAME

**Comment by dwmw2** [comment]
Oh, stupid dwmw2, no biscuit. I "fixed" this the wrong way round.

On POSIX platforms, if stdin is redirected from a pipe then any interactive prompting doesn't work; it just dies with
```
Please enter your username and password.
Username:fgets (stdin): Resource temporarily unavailable
```
... which is reasonable enough. I "fixed" the Windows build to behave differently, and open `CONIN$` when stdin isn't a console. But I didn't even do that *just* for the interactive stuff; I did it for the `--passwd-on-stdin` bit too. So now it was completely ignoring stdin in all circumstances, and reading from the console.

To be consistent with other platforms we *want* to use stdin, never `CONIN$`. But the reason for using `ReadConsoleW()` (and thus requiring it to be a console) is the stupid charset handling under Windows. Let me see if I can get something working....

Can you try http://david.woodhou.se/win32-stdin.patch on a real Windows box? ISTR there are issues with wine in this area which make my local testing invalid.

It works for the actual console:
```
 $ ./openconnect.exe --passwd-on-stdin vpn.intel.com 
fixme:winediag:start_process Wine Staging 1.9.18 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
foo♥
Password is 'foo♥'
```
... but for stdin it doesn't:
```
 $ ./openconnect.exe --passwd-on-stdin vpn.intel.com  <<< "foo♥"
fixme:winediag:start_process Wine Staging 1.9.18 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
Password is 'fooâ™¥
'
POST https://vpn.intel.com/
```
```

**Comment by nathanila** [comment]
I can try the patch if you send me openconnect.exe.  To get past the email filters, you will probably have to upload it to Dropbox, Google Drive or some other place and share the link.

 

-Nathan

**Comment by dwmw2** [comment]
http://david.woodhou.se/gh101/openconnect.exe
http://david.woodhou.se/gh101/libopenconnect-5.dll

**Comment by nathanila** [comment]
The following doesn’t work because echo adds a newline character to the password and this is passed to openconnect.exe which passes the newline to the server which fails the login.

 

echo “password” | openconnect.exe …

 

However, the following does work.

 

echo | set /p="password" | openconnect.exe …

 

-Nathan

**Comment by dwmw2** [comment]
Ok, I'll investigate the CR vs. LF handling for end-of-line. That ought to be stripped correctly. But what about non-ASCII characters? If you use a password of `naïve` or for added fun `foo♥` as in my example, does that work?

Note that by 'work' I mean printing it out correctly because I added a line to make it do that. Obviously I'm not asking if you can successfully log into your VPN server with those passwords.

**Comment by dwmw2** [comment]
I've updated the executables linked above, to help debug the CR/LF problem. Please could you test again and show me the output?

**Comment by horar** [comment]
> echo xxx | ....
stdin read 5: 32 10
Password is '"xxx"
.....

**Comment by dwmw2** [comment]
OK, thanks. Will fix. How about non-ASCII?

**Comment by horar** [comment]
>echo foo♥ | ...
stdin read 6: 32 10
Password is 'foo

**Comment by dwmw2** [comment]
Gr. What about a character that *is* in your legacy chars etc, perhaps `ï` ?

**Comment by horar** [comment]
>echo fooï | ...
stdin read 6: 32 10
Password is 'fooi

**Comment by dwmw2** [comment]
Oh, Windows is a pile of crap. Not sure there is any sane way of actually reading  non-ASCII reliably from stdin, which is why we used the console functions in the first place. Will take another look.

**Comment by horar** [comment]
heh, yes ... working on multiplatform stuff is always a challenge :-)

what about trimmint EOLs? other characters are fine for us (we don't care in this case)
> std::string str;
str.erase(std::remove(str.begin(), str.end(), '\n'), str.end());

(didn't try)

**Comment by nathanila** [comment]
I ran openconnect.exe with --dump-http-traffic.

 

When I pass naïve in for the password, it is printed on the screen as <password>na<ve</password>.  The < in the password isn’t going to work in the XML.

 

When I pass foo♥ in for the password, it is printed on the screen as…

 

<password>foo♥</password>

 

So, one works and the other doesn’t.  I wonder if it has to do with the code page that the command line uses.

 

-Nathan

**Comment by dwmw2** [comment]
@nathanila Those tests were using `--passwd-on-stdin`?  Does it work correctly without that, when you are using the console to enter the passwords? 

(Note that there is potential for bugs where what it prints to the screen isn't what it actually sent on the wire, but those are less likely)

**Comment by nathanila** [comment]
The previous tests were using –passwd-on-stdin.  Without that, naïve shows up on the console as <password>naïve</password> after I enter it manually at the Password: prompt.  Also, foo♥ shows up on the console as <password>foo♥</password> as well.

 

-Nathan

**Comment by dwmw2** [comment]
Right. So without `--passwd-on-stdin` it works fine. And the proposed patch for makng `--passwd-on-stdin` work... doesn't. 

I am reluctant to apply it when  it doesn't work correctly.

**Comment by ExSport** [comment]
CMD is running with CP437 by default (US English). You should try to change it to something like UTF8 to support all chars?
``chcp 65001``
http://ss64.com/nt/chcp.html
Also to see letters right you need to change font to TRUE TYPE, like LUCIDA CONSOLE.

**Comment by dwmw2** [comment]
I wonder if calling [`_setmode()`](https://msdn.microsoft.com/en-us/library/tw4k6df8.aspx) on stdin is the way to do it.

**Comment by nathanila** [comment]
The current patch works much better and resolves some issues but not all issues.  If the work were to stop now, it is worth checking in the patch.

 

-Nathan

**Comment by nathanila** [comment]
I executed chcp 65001 in a command prompt.  When I try to paste naïve into the console, I get nave.  The ï is completely missing.  This seems to be a step backwards.

 

-Nathan

**Comment by dwmw2** [comment]
> The current patch works much better and resolves some issues but not all issues. If the work were to stop now, it is worth checking in the patch.

I am reluctant to add broken ASCII-only functionality. I'd really like to have it *working*.

**Comment by ExSport** [comment]
@nathanila Problem on your side.
Change Raster Font to TrueType as I described:
![image](https://cloud.githubusercontent.com/assets/1260408/18960379/ca6bd652-8669-11e6-97a2-c53c5f34bec8.png)

**Comment by dwmw2** [comment]
@ExSport OK... so once the basic echo commands to the console are working, does it then work when you echo the same to `openconnect --passwd-on-stdin` using the above binaries? Apart from the CR/NL problem, of course.

**Comment by nathanila** [comment]
I set the font to “Consolas”.  I changed the code page to 65001.  This command still corrupts the password.

 

C:\Temp>echo | set /p=naïve| "C:\Program Files (x86)\OpenConnect\openconnect.exe" --passwd-on-stdin --user=Test server

Password is 'naÃ¯ve'

 

C:\Temp>echo | set /p=pass♥| "C:\Program Files (x86)\OpenConnect\openconnect.exe" --passwd-on-stdin --user=Test server

Password is 'passâ™¥'

 

If I switch back to code page 437, then ï is changed to a ‹ and the heart is fine.

 

C:\Temp>chcp 437

Active code page: 437

 

C:\Temp>echo | set /p=naïve| "C:\Program Files (x86)\OpenConnect\openconnect.exe" --passwd-on-stdin --user=Test server

Password is 'na‹ve'

 

C:\Temp>echo | set /p=pass♥| "C:\Program Files (x86)\OpenConnect\openconnect.exe" --passwd-on-stdin --user=Test server

Password is 'pass♥'

 

I set the font to “Lucida Console” and I get the same behavior.

 

Note: I am running on Window 7 64-bit.

 

-Nathan

**Comment by dwmw2** [comment]
That's... confusing. Is something still set to the Windows-1252 charset?

The word `naïve` in UTF-8 is `6e 61 c3 af 76 65` and those are the bytes we read on stdin.

Now, if the `fgetws()` call in OpenConnect is assuming its input is Window-1252, it interprets those same bytes to mean `naÃ¯ve`. And then we print those characters to the screen through translations which are working sanely.

The second example works the same way. Your `pass♥` in UTF-8 is `70 61 73 73 e2 99 a5` and those bytes interpreted as Windows-1252 would be `passâ™¥`

Third example.... `naïve` in CP437 is  `6e 61 8b 76 65`. But in Windows-1252, the byte `8b` means `‹` so it's interpreted as `na‹ve`. All relatively sane so far, except the question of why the Windows `fgetws()` function is interpreting the input bytes as Windows-1252 instead of the actual code page that was set.

The last one is slightly confusing. Wikipedia's CP437 page suggests that the `♥` character actually is in CP437, which I hadn't realised. I had meant to use a character which *wasn't* going to be in the legacy code pages. So your last password `pass♥` in CP437 is `70 61 73 73 03` — although `iconv` doesn't seem to like the ♥ character. Maybe Windows just has a special case for the characters below 0x20, which are control characters in ASCII? And it treats `03` as ♥ in both CP437 and Windows-1252?

If you start a new console and don't use `chcp` at all, what happens then? Was it *really* in CP437 to start with, or could the default have been Windows-1252?

**Comment by dwmw2** [comment]
I've updated the executables above, with a call to `_setmode(_fileno(stdin), _O_U16TEXT);`.

There's a distinct possibility that'll just interpret the incoming bytes as UTF-16LE instead of Windows-1252, which will break it even for ASCII characters... but maybe not. Can you test again please?

**Comment by nathanila** [comment]
I opened a brand new command prompt.

C:\Temp>chcp
Active code page: 437

C:\Temp>echo | set /p=naïve
naïve

C:\Temp>echo | set /p=pass♥
pass♥

C:\Temp>chcp 65001
Active code page: 65001

C:\Temp>echo | set /p=naïve
naïve

C:\Temp>echo | set /p=pass♥
pass♥

I don't know if this information makes things easier or worse to understand.

**Comment by nathanila** [comment]
I downloaded the binaries into C:\Program Files (x86)\OpenConnect.  I opened a new command prompt and here's what happened.

C:\Program Files (x86)\OpenConnect>chcp
Active code page: 437

C:\Program Files (x86)\OpenConnect>echo | set /p=naïve| "C:\Program Files (x86)\OpenConnect\openconnect.exe" --passwd-on-stdin --user=Test _server_
stdin read 2: 24942 30347
Password is '慮皋'                  // On the screen it looks like blocks
 ^C

C:\Program Files (x86)\OpenConnect>echo | set /p=pass♥| "C:\Program Files (x86)\OpenConnect\openconnect.exe" --passwd-on-stdin --user=Test _server_
stdin read 2: 24944 29555
Password is '慰獳'                  // On the screen it looks like blocks
 ^C

C:\Program Files (x86)\OpenConnect>chcp 65001
Active code page: 65001

C:\Program Files (x86)\OpenConnect>echo | set /p=naïve| "C:\Program Files (x86)\OpenConnect\openconnect.exe" --passwd-on-stdin --user=Test _server_
stdin read 3: 44995 25974
Password is '慮꿃敶'                  // On the screen it looks like blocks
 ^C

C:\Program Files (x86)\OpenConnect>echo | set /p=pass♥| "C:\Program Files (x86)\OpenConnect\openconnect.exe" --passwd-on-stdin --user=Test _server_
stdin read 3: 29555 39394
Password is '慰獳駢'                  // On the screen it looks like blocks
 ^C

**Comment by dwmw2** [comment]
Ew, so Windows has *two* code pages active at the same time for a given application. There's the ANSI code page, and the OEM code page. In your case, one is CP437 and the other is Windows-1252. And when we read from stdin we have no idea whether it's from the console (in the OEM code page CP437), or from somewhere else like a file (in Windows-1252). In this case it's from a pipe and we have no way of knowing... we treat it as CP437 when it's actually Windows-1252. 

I think Windows is just too broken to make this work coherently at all.

**Comment by dwmw2** [comment]
Reading http://superuser.com/questions/323024/how-to-pipe-windows-dir-in-ansi-codepage ... if you run `cmd /U` and then run the latest binaries, what happens?

**Comment by nathanila** [comment]
It appears that openconnect.exe shouldn’t do anything different.  The user has to set the right code page before running openconnect.  If the code page is set 1252, then naïve works but pass♥ does not.  If the code page is set to 437, then pass♥ works but naïve does not.

 

C:\Temp>chcp 1252

Active code page: 1252

 

C:\Temp>echo | set /p=naïve| "C:\Program Files (x86)\OpenConnect\openconnect.exe" --passwd-on-stdin --user=Test server

Password is 'naïve'

 

C:\Temp>echo | set /p=pass♥| "C:\Program Files (x86)\OpenConnect\openconnect.exe" --passwd-on-stdin --user=Test server

Password is 'pass?'

 

C:\Temp>chcp 437

Active code page: 437

 

C:\Temp>echo | set /p=naïve| "C:\Program Files (x86)\OpenConnect\openconnect.exe" --passwd-on-stdin --user=Test server

Password is 'na‹ve'

 

C:\Temp>echo | set /p=pass♥| "C:\Program Files (x86)\OpenConnect\openconnect.exe" --passwd-on-stdin --user=Test server

Password is 'pass♥'

 

-Nathan

**Comment by horar** [comment]
Don't know what can be done something on GUI part of project with this problem. Closing here, the communication can continue in openconnect mailing list.

**Comment by AshrazRashid** [comment]
hi , i m using this script in window 10 type Pass.txt | "C:\Program Files (x86)\OpenConnect\openconnect.exe" --passwd-on-stdin <Pass.txt  --user=Username vpn.server.com
 facing issue "Authentication error; cannot obtain cookie" help me to sort out.

**Comment by DomHudson** [comment]
Posting here for others who experience this on Linux; I got the same issue as I accidentally supplied both the `--passwd-on-stdin` and the `--key-password` flags. Removing the latter flag, all worked fine.


Error message:
```
Username:fgets (stdin): Resource temporarily unavailable
```

**Comment by bhaskarkc** [comment]
`echo -n "passwordtext" | sudo openconnect --password-on-stdin` works just fine as `-n` does not prints extra line.
