### ISSUE TITLE
Win7 TAP Connection "unidentified network"

### ISSUE THREAD

**Issue by walt-k** [openconnect/openconnect-gui#104]
Hello
On three different Windows 7 computers I encounter the same behaviour:
after successful VPN establishment, Windows' TAP Connection is in Status="Unidentified network" and Connectivity="No network access".
So traffic destined to internal network goes to public, regardless of routing table.
May be I'm doing something wrong. Please explain, step by step how to install this program and how establish VPNs using this program.
Or what additional information should I provide here to localize problem?
Regards
Walter

**Comment by walt-k** [comment]
Well. The problem is that vpnc-script.js does not set ARP for next hop for added routes.
According to sources of TAP-Windows, MAC address of far end is composed from MAC address of TAP Adapter +1 in byte #2 (in network order).
I think stuff must be implemented.
Best regards

**Comment by horar** [comment]
hi, is this still valid?

**Comment by horar** [comment]
Hi @walt-k , could you please attach a patch to this? (actual wip version of script is [here](https://github.com/horar/vpnc-scripts). Thanks

**Comment by horar** [comment]
Ths project is about GUI only. Most suitable place to discuss/fix is [mailiing list of openconnect](http://www.infradead.org/openconnect/mail.html)
