### ISSUE TITLE
Change Traffic Light To Yellow When Disconnecting

### ISSUE THREAD

**Issue by spetragl** [openconnect/openconnect-gui#105]
Just like when you Connect and and turn the Traffic light yellow running the connect script, why not turn the Traffic light yellow when running the Dis-connect script.
Of course keep it red when finished.

**Comment by horar** [comment]
I'm afraid that disconnect is too fast to indicate disconnecting state; anyway, I can update image on this stage.

**Comment by spetragl** [comment]
Thanks
