### ISSUE TITLE
Authentication error; cannot obtain cookie

### ISSUE THREAD

**Issue by tjmcwiz** [openconnect/openconnect-gui#112]
Open connect was working fine but now I can't connect. Any suggestions on where to start looking? The log says authentication error, cannot obtain cookie but that's not much to go on ...

The Log shows the following (some items masked):

POST https://sslvpn.xxxxxx.com/
Attempting to connect to server xxx.xxx.xxx.xxx:443
Connected to xxx.xxx.xxx.xxx:443
SSL negotiation with sslvpn.xxxxxx.com
Server certificate verify failed: signer not found
Connected to HTTPS on sslvpn.xxxxxx.com
Got HTTP response: HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Cache-Control: no-cache
Pragma: no-cache
Connection: Keep-Alive
Date: Tue, 14 Jun 2016 15:35:18 GMT
X-Frame-Options: SAMEORIGIN
X-Aggregate-Auth: 1
HTTP body chunked (-2)
XML POST enabled
Please enter your username and password.
Saving group: sslvpn
POST https://sslvpn.xxxxxxx.com/
Got HTTP response: HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Cache-Control: no-cache
Pragma: no-cache
Connection: Keep-Alive
Date: Tue, 14 Jun 2016 15:35:22 GMT
X-Frame-Options: SAMEORIGIN
X-Aggregate-Auth: 1
HTTP body chunked (-2)
XML POST enabled
Please enter your username and password.
Select form: group_list
Text form: username
Password form: password
POST https://sslvpn.xxxxx.com/
Got HTTP response: HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Cache-Control: no-cache
Pragma: no-cache
Connection: Keep-Alive
Date: Tue, 14 Jun 2016 15:35:28 GMT
X-Frame-Options: SAMEORIGIN
X-Aggregate-Auth: 1
HTTP body chunked (-2)
Please enter your username and password.
Login failed.
Authentication error; cannot obtain cookie
Disconnected

**Comment by horar** [comment]
I suspect the reason may be "Login failed", could u please double-check that your login credentials are valid and your account is not locked?

**Comment by tjmcwiz** [comment]
Thanks - I was able to track this down to the admin changing the group name ........
