### ISSUE TITLE
Windows Packaging: libstoken-1.dll missing

### ISSUE THREAD

**Issue by MartinOehler** [openconnect/openconnect-gui#114]
Hello,

I'm trying to reproduce the windows build of openconnect to trace a possible bug. The openconnect.exe has been compiled but I'm getting an error during the NSIS packaging:

```
Run CPack packaging tool...
"C:\Program Files (x86)\CMake\bin\cpack.exe" --config ./CPackConfig.cmake
CPack: Create package using NSIS               
CPack: Install projects                            
CPack: - Run preinstall target for: openconnect-gui              
CPack: - Install project: openconnect-gui              
CPack: -   Install component: App            
warning: target 'libstoken-1.dll' is not absolute...
warning: target 'libstoken-1.dll' does not exist...
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/GetPrerequisites.cmake:800 (message):
C:/Qt/Tools/mingw492_32/bin/objdump.exe failed: 1
C:/Qt/Tools/mingw492_32/bin/objdump.exe: 'libstoken-1.dll': No such file
```
There are multiple dlls inside the nsis directory but I can't find `libstoken-1.dll`. 

Might the commit of this file be misssing?

Thanks,
Martin

**Comment by horar** [comment]
Ups, sorry ... it stay on my file system; git ignore libraries on my drive...

**Comment by MartinOehler** [comment]
Thanks - could you please add the file to the repository (the 1.4 release might take some time i assume)?

**Comment by horar** [comment]
yeap, ... I will add that dll today, on evening... I don't have access to my dev-machine right now
(just wanna track the task, somewhere)

**Comment by MartinOehler** [comment]
Great.
