### ISSUE TITLE
Compiling dev v1.4 fails on Windows

### ISSUE THREAD

**Issue by ExSport** [openconnect/openconnect-gui#117]
Please can you help me with environment configuration so dev branch of openconnect-gui will successfully compile on Windows with help of "build_mingw@win.cmd"?
I installed (with no extra custom reconfig):
- Qt\5.6\mingw49_32
- cmake-3.6.0-win32-x86
- LLVM-3.8.0-win32

From CMD file it seems it is everything needed for successful compile.
Running "cmake" passed without errors but "mingw32-make" generates them and stops:
```
c:\xxx>build_mingw@win.cmd
"======================================================================="
" Preparing environment..."
"======================================================================="
Setting up environment for Qt usage...
Setting up environment for 'mingw32' usage...
Setting up environment for CMake usage...
Setting up environment for 7Z usage...
Setting up environment for 'clang' usage...
"======================================================================="
" Preparing sandbox..."
"======================================================================="
"======================================================================="
" Generating project..."
"======================================================================="
-- The CXX compiler identification is GNU 4.9.2
-- Check for working CXX compiler: C:/Progs/Qt/Tools/mingw492_32/bin/g++.exe
-- Check for working CXX compiler: C:/Progs/Qt/Tools/mingw492_32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is GNU 4.9.2
-- Check for working C compiler: C:/Progs/Qt/Tools/mingw492_32/bin/gcc.exe
-- Check for working C compiler: C:/Progs/Qt/Tools/mingw492_32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/xxx/build-release
"======================================================================="
" Compiling..."
"======================================================================="
Scanning dependencies of target openconnect-gui_automoc
[  4%] Automatic moc, uic and rcc for target openconnect-gui
Generating moc source openconnect-gui_automoc.dir/dialog/moc_editdialog.cpp
Generating moc source openconnect-gui_automoc.dir/dialog/moc_logdialog.cpp
Generating moc source openconnect-gui_automoc.dir/dialog/moc_mainwindow.cpp
Generating moc compilation openconnect-gui_automoc.cpp
Generating ui header ui_editdialog.h
Generating ui header ui_logdialog.h
Generating ui header ui_mainwindow.h
Generating qrc source openconnect-gui_automoc.dir/qrc_openconnect-gui.cpp
[  4%] Built target openconnect-gui_automoc
mingw32-make[2]: *** No rule to make target '../src/scm_version.cmake', needed by 'src/openconnect-gui.rc'.  Stop.
CMakeFiles\Makefile2:153: recipe for target 'src/CMakeFiles/openconnect-gui.dir/all' failed
mingw32-make[1]: *** [src/CMakeFiles/openconnect-gui.dir/all] Error 2
makefile:126: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
"======================================================================="
" Packaging..."
"======================================================================="
-- Configuring done
-- Generating done
-- Build files have been written to: C:/xxx/build-release
mingw32-make: *** No rule to make target 'package'.  Stop.
mingw32-make: *** No rule to make target 'package_source'.  Stop.
```
Please can someone direct me how to fix it so I can test newest build?
Many thanks!

**Comment by horar** [comment]
Hi, looks like you try build the project from snapshot archive? This functionality is not finished yet. CMake generate all version s strings from git repository and these version numbers are used few other files (for about dialog, RC file on window etc.). So if you clone the project, it should work.
Don't worry, it will be definitely supported with 1.4-rc1, it is more-less working on my desktop, just isn't well tested to submit...

**Comment by ExSport** [comment]
@horar Many thanks for help! It works now! So easy with your help :+1: 
Unfortunately latest build still doesn't work when using "System Store" for certs (same as v1.3) and also GUI get frozen when local certs are used (it worked in v1.3)
It freeze at time it should ask for passphrase of the private key when clicking on SAVE.
Btw. in console it works ok (it asks for passphrase but from console passing cert from store seems not to be supported)

**Comment by horar** [comment]
Hi @ExSport pls. install & try v1.4.0; if you will have still the problem with Store, pls. drop new ticket, thanks

**Comment by ExSport** [comment]
@horar Hello
Unfortunately same problem as my custom compile described above. It means using certstore doesn't work and importing separate certs will freeze whole GUI at time it should ask for password for private key when you clicked on SAVE button.
Tested on Windows 7 and Windows 10 (all 64bit)
Error when trying to use certstore:
```
2016-08-11 15:26 POST https://vpn-concentrator.int/
2016-08-11 15:26 Attempting to connect to server 1.2.3.4:443
2016-08-11 15:26 Using certificate file C:/Progs/OpenConnect/tmp-certp13236
2016-08-11 15:26 Using system key system:win:id=11ba3d87f7572ae5ac22674bd6b3f7232014592d;type=privkey
2016-08-11 15:26 Error importing system key system:win:id=11ba3d87f7572ae5ac22674bd6b3f7232014592d;type=privkey: The requested data were not available.
2016-08-11 15:26 Loading certificate failed. Aborting.
2016-08-11 15:26 Failed to open HTTPS connection to vpn-concentrator.int
2016-08-11 15:26 Authentication error; cannot obtain cookie
2016-08-11 15:26 Disconnected
```
Will create new issue on it as it seems it is not computer specific (two different OSes, both have same problem). Thx

**Comment by horar** [comment]
Is it possible to try official binary i.e. with UAC etc.? (just to be sure that UAC is not a problem when accessing cert/key store)

**Comment by ExSport** [comment]
Will try it. But not only cert store doesn't work. It has problem also with extracting private key at time it should ask for password. Instead of asking for password the whole GUI will stuck so you have to kill the process. From console passing password works so it seems like GUI problem.
Will let you know with UAC enabled.
But it seems you can't reproduce it so it should be something specific what I have in two different OS versions...weird...
