### ISSUE TITLE
I need rebuild libopenconnect-5.dll,but libgnutls not work

### ISSUE THREAD

**Issue by shanecode** [openconnect/openconnect-gui#119]
openconnect project libgnutls is 28

openconnect-gui project  libgnutls is 30 

could you share the openconnect project source for libgnutls30.dll  ?

**Comment by nmav** [comment]
You can get gnutls' builds for win32 at: ftp://ftp.gnutls.org/gcrypt/gnutls/w32/

**Comment by shanecode** [comment]
Thank you
