### ISSUE TITLE
Log file can't be created

### ISSUE THREAD

**Issue by nielspeen** [openconnect/openconnect-gui#12]
I see this error in the log after connecting:

```
Could not open C:/Users/Niels/AppData/Local/Temp\vpnc.log
```

The vpnc.out file is created correctly, but vpnc.log is indeed missing.

**Comment by sssimha** [comment]
Hi @nmav ,

I'm still getting this issue in 1.5.3.

Windows 10 machine, connecting to an ocserv v0.11 server.

**Comment by horar** [comment]
@sssimha could you please provide log file? Which OS version?

**Comment by sssimha** [comment]
Hi @horar 

I could not find the vpnc.log file, I had to manually copy the log from the gui and attach it here:
[openconnect-gui_log_201902141619ET.log](https://github.com/openconnect/openconnect-gui/files/2866839/openconnect-gui_log_201902141619ET.log)

**Comment by horar** [comment]
Do you use other VPN clients? free or official cisco?
