### ISSUE TITLE
Connection "lost" (broken) after appx. 30 seconds

### ISSUE THREAD

**Issue by jmichler** [openconnect/openconnect-gui#120]
Hi,

somhow the openconnect.exe included in the v1.2 build causes some trouble for me. The connection is setup good, I can do a ping to a host in my network (where both name resolution and routing work fine), I can also establish an ssh connection. However after appx. 30 seconds the connection breaks down (no more pings are working). When looking into the openconnect -vv log I see nothing strange here. It seems that the connection between the network driver and the openconnect process is just lost.

Any ideas on that? I've tried to build either openconnect or openconnect-gui on my own, though the documentation are rather "short" and I didn't manage to do this so far. What would be the best documentation starting point there?

The problem is similar to what is described here for openvpn:
http://superuser.com/questions/1089700/open-vpn-connection-loses-internet-access-after-30-seconds

Is there any "free test-server" I could use to make sure it is not relevant to the server I'm using? Though that server is working fine with openconnect on linux for years.

BR
Johannes

**Comment by horar** [comment]
Hi, could you please try newest version? Version 1.2 is quite old. And v1.4.0 is already released, with console fresh openconnect console/gui clients and latest tap drivers; thanks.

**Comment by jmichler** [comment]
Hi,

thanks for the update. I've installed the brand new 1.4.0 (previously I was on 1.3, don't know why I wrote 1.2, sorry). Though the problem with 1.4 is the same, connection is working for some seconds and then breaks.

BR
Johannes

**Comment by horar** [comment]
okey, may be try add log output, so we can see what's happening there.
(please, just close-open the log window - there is an an issue that vpnc script log is not loaded automatically)
thanks

**Comment by jmichler** [comment]
Hi,

well as of a sudden  it is working now. I think it was somehow managed by setting REDIRECT_GATEWAY_METHOD = -1 in vpnc-script.js and calling route add manually.

Now however the program interfers with OpenVPN (which uses the same network adapter; I do not use both concurrently of course). Somehow my manually added route from openconnect is applied also for  the openvpn connection. That wouldn't be so bad, but the bigger problem is that the dns-server is changed during openconnect-connect to manual; and that is not set to automatic back then during the OpenVPN-Connection. Any idea on that? Is there a "better cleaning up" vpnc-js-script? Or a more manual approach that simply sets manually defined sub-nets (2 in my case) and a dns-server on-connect and reset all that on disconnect? In the linux-Version I've got something as:

CISCO_SPLIT_INC=3
CISCO_SPLIT_INC_0_ADDR=10.0.0.0
CISCO_SPLIT_INC_0_MASK=255.0.0.0
CISCO_SPLIT_INC_0_MASKLEN=8
CISCO_SPLIT_INC_1_ADDR=1.2.3.4
CISCO_SPLIT_INC_1_MASK=255.255.255.224
CISCO_SPLIT_INC_1_MASKLEN=27
CISCO_SPLIT_INC_2_ADDR=5.6.7.8
CISCO_SPLIT_INC_2_MASK=255.255.255.240
CISCO_SPLIT_INC_2_MASKLEN=28

(I anonymized 1.2.3.4 and 5.6.7.8 obviously)

Is something like that available for the windows-version?

BR
Johannes

**Comment by jmichler** [comment]
After adding manual commands in vpnc-js both on connect and disconnect everything works as needed. Thanks a lot, that is really helping me!
