### ISSUE TITLE
Feature Request: GUI setting option for equivalence of --juniper setting

### ISSUE THREAD

**Issue by irakhlin** [openconnect/openconnect-gui#121]
Are there any plans to add juniper support to the GUI in the new version using the 5.3 API? I have been able to use my own build of openconnect.exe wrapped in a batch script to achieve this without any issue. I also recently noticed the 5.3 API branch available here and it seems to work just fine. It would be nice to be able to have this as a checkbox in the profile setting..

**Comment by horar** [comment]
Hi, there are no exact plans, looks like it's still marked as experimental support.
And I don't have access to do that equipment.

May be tel me more how you manage to setup it and if it will be trivial, we can look at it (or create a pull request)

**Comment by nmav** [comment]
Support is experimental but it seems to work fine for most cases. Switching to the juniper protocol can be done with the call: ```openconnect_set_protocol(vpninfo, "nc")```

It can be an advanced option to switch to this protocol or so.

**Comment by irakhlin** [comment]
Hi Horar,

Yes this is definitely experimental in the openconnect library, I will say I have been using it since they had committed the feature and it has been fairly decent without any specific problems. Using the openconnec-gui feature/openconnect_api_5.3 branch passing a simple pass --juniper as one of the openconnect.exe parameters. I will say that I have had to use --no-xmlpost on some juniper servers to get it to connect but the one work uses seems to work without it. It may be nice to had an "advanced override" field letting you pass though things like the --juniper flag, --no-xmlpost, --dtls-ciphers, ect that are not available in the GUI. 

I have not had a lot of time to look at this myself but I will take a look myself or if you have already made changes I am more than happy to do testing. I had minimum experience with QtCreator so I burned some time there getting the project setup.

**Comment by irakhlin** [comment]
Just wanted to add; it seems this should be very possible.. Quickly looking at things I added:
openconnect_set_protocol(this->vpninfo,"nc"); to line 361 in vpninfo.cpp... The end result is that I am not getting the proper and expected prompts to authenticate and sign into the server where as without setting this I get:
2016-08-24 16:53 XML response has no "auth" node
2016-08-24 16:53 Authentication error; cannot obtain cookie

With this I can fully authenticate to the server after which the GUI client crashes with the following error:Failed to spawn script 'C:/Program Files (x86)/OpenConnect API5-test\vpnc-script.js' for connect: The specified resource type cannot be found in the image file.

This could also be sloppiness on my part and messing something up but I will take a look.

**Comment by TestUser013** [comment]
Hi All,
I would like to use openconnect for connecting to juniper vpn at windows machine. Could somebody give me link where I can download openconnect.exe with support --juniper flag ?
Thank you.

**Comment by horar** [comment]
@TestUser013 hi, didn't try, but v1.4.1 gui installer contains console version as well; you can try that for now. More recent version will come with next gui release.

**Comment by TestUser013** [comment]
@horar , I have download v1.4.1, but there are no  --juniper flag :(

**Comment by horar** [comment]
@TestUser013 did you try set the protocol? 

>        --protocol=PROTO
              Select VPN protocol PROTO to be used for the connection. Supported  protocols  are  anyconnect
              for  Cisco  AnyConnect (the default), and nc for experimental support for Juniper Network Con-
              nect (also supported by Junos Pulse servers).

**Comment by TestUser013** [comment]
@horar there are no --protocol flag. I have attached parameter list
[log.txt](https://github.com/openconnect/openconnect-gui/files/502974/log.txt)

**Comment by horar** [comment]
@TestUser013 did you try use it?
Yes, it's probably missing in '--help' list or it is experimental (as far I see, there is still some work in openconnect library).
But this flags is mentioned in openconnect manual.

**Comment by TestUser013** [comment]
@horar I'm getting this help than I type "openconnect.exe --protocol=NC sslvpn.server.name" or "openconnect.exe --protocol=PROTO sslvpn.qad.com" in command line

**Comment by horar** [comment]
hmm, will check it....
