### ISSUE TITLE
Openconnect does not forward traffic through tun0

### ISSUE THREAD

**Issue by persianpars** [openconnect/openconnect-gui#123]
When i use openconnect sometimes a i'm connected to vpn, sometimes i'm not.  
this is the output of `route` when i'm connected to vpn.
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         *               0.0.0.0         U     0      0        0 tun0
default         gateway         0.0.0.0         UG    600    0        0 wlp3s0
10.10.0.0       *               255.255.240.0   U     0      0        0 tun0
6d7b7202.rdns.s gateway         255.255.255.255 UGH   0      0        0 wlp3s0
link-local      *               255.255.0.0     U     1000   0        0 wlp3s0
192.168.1.0     *               255.255.255.0   U     600    0        0 wlp3s0
```
and this is the output when i'm not:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gateway         0.0.0.0         UG    600    0        0 wlp3s0
10.10.0.0       *               255.255.240.0   U     0      0        0 tun0
6d7b7202.rdns.s gateway         255.255.255.255 UGH   0      0        0 wlp3s0
link-local      *               255.255.0.0     U     1000   0        0 wlp3s0
192.168.1.0     *               255.255.255.0   U     600    0        0 wlp3s0
```
what could be the issue here, why is it that only **sometimes** the route is created?
***
I'm using ubuntu 15.10 and
OpenConnect v7.06

**Comment by horar** [comment]
Hi, just a remark - here we tracks mostly GUI issues; if you wish more quickly/accurate answer, you can try follow mailing list mentioned at http://www.infradead.org/openconnect/mail.html what is about console openconnect client.

Anyway, if you can reproduce the issues, please save the logs in both cases. It will speed up to solve app issues :-)
May be we can we can help you. But from attached route output is not complete information to analyse the problem.

**Comment by persianpars** [comment]
Oh ok sorry.

By logs you mean running `openconnect` using -v (verbose)?

**Comment by horar** [comment]
hi, no problem :-)
yes, you can start with verbose mode ... just keep in mind "security warnings" on that page to keep your secret!!

**Comment by persianpars** [comment]
i reproduced it but the logs are not differecnt (except on sessionid and ...)  
here are the log files
[openconnect log files](https://gist.github.com/persianpars/6afb49628b61cc95360f6c7c0e3c2f53)

**Comment by persianpars** [comment]
Well looks like NetworkManager and openconnect conflict with eachother.  
The solution is to use network-manager-openconnect.  
But looks like there is no way we can skip the [two step verification](http://askubuntu.com/questions/753333/automatically-connect-an-openconnect-vpn-connection) (specially if i want to activate it using nmcli without any gui)

**Comment by jimaldon** [comment]
But network-manager-openconnect doesn't seem to work with juniper VPNs. 

So with the cli `openconnect --juniper` solution, openconnect doesn't route my traffic through the VPN.

**Comment by horar** [comment]
@jimaldon hi, sorry - but this projest is just about Qt GUI on top of openconnect library. Please discuss your issues in openconnect mailing list or in network-manager issue tracker.
