### ISSUE TITLE
Better Warning message if there is a Name Missmatch .

### ISSUE THREAD

**Issue by xamor** [openconnect/openconnect-gui#135]
If there is a DNS-Name Missmatch with the provided certificate openconnect says: "It seems like you are connecting to this server the first time" this message is wrong and dangerous

**Comment by horar** [comment]
I agree, we should put there something more descriptive, so the user is aware what's happenning when this dialog appears and when it is accepted.

**Comment by nmav** [comment]
> If there is a DNS-Name Missmatch with the provided certificate openconnect says: "It seems like you are connecting to this server the first time" this message is wrong and dangerous

I am not sure I follow the argumentation. Why is this message wrong? The client implements trust on first use if the PKIX verification doesn't work so the message is certainly correct.

**Comment by horar** [comment]
I don't plan write scaring texts, my idea is update the text to similar notification like e.g. putty/scp etc. does when connecting first time or cert-signature of GW is changed.
