### ISSUE TITLE
Dialog for the Welcome Message

### ISSUE THREAD

**Issue by xamor** [openconnect/openconnect-gui#136]
For some server administrators it is important to inform users about changes on the server via Welcome Message. Openconnect GUI shows it only in the log. Maybe it would be good to show it only if there is a new/unread Message.

**Comment by horar** [comment]
hi, if you can see desired kind of messages in log - it should not be a problem to show a dialog to user after connection (or later, with new - already implemented logger).

May be drop few lines from your log, may speed-up implementation in UI.
