### ISSUE TITLE
ReadConsole() failed: The handle is invalid

### ISSUE THREAD

**Issue by nathanila** [openconnect/openconnect-gui#138]
I installed OpenConnect 1.4.1 Windows GUI with console program.  I am trying to use echo to send my password to openconnect.exe.  However, I am getting an error message.  Here's the sanitized console output.

echo abc123 | "C:\Program Files (x86)\OpenConnect\openconnect.exe" --passwd-on-stdin --user=nreynold_us  --no-proxy --disable-ipv6 my.vpn.com

 POST https://my.vpn.com/
 Attempting to connect to server xxx.xxx.xxx.xxx:443
 SSL negotiation with my.vpn.com
 Connected to HTTPS on my.vpn.com
 Got HTTP response: HTTP/1.0 302 Temporary moved
 POST https://my.realvpn.com/
 Attempting to connect to server xxx.xxx.xxx.xxx:443
 SSL negotiation with my.realvpn.com
 Connected to HTTPS on my.realvpn.com
 XML POST enabled
 Use of this network and applications is intended solely for authorized users. The use of these resources is subject to policies; access may be monitored and logged, to the extent permitted by law, in accordance with policies. Unauthorized access or use may result in termination of your access, disciplinary action and/or civil and criminal penalties. Further information about security and privacy policies is available at the Policy Portal.
 Password: ReadConsole() failed: The handle is invalid.

 POST https://my.realvpn.com/
 XML response has no "auth" node
 Failed to obtain WebVPN cookie

**Comment by horar** [comment]
Hi, this was already reported in #101 ; anyway, if you want more accurate answer, the openconnect mailing list could be better place to ask :-)
