### ISSUE TITLE
Socket remains open after cancelling the connection 

### ISSUE THREAD

**Issue by AriaShishegaran** [openconnect/openconnect-gui#139]
for each time I cancel or get a rejection from my server, a socket remains open on my Windows 10 64bit machine. so if I cancel 3 times, I will face 3 dialogs that I should click on OK. why does this happen? if the connection is not successful why should a socket remain open?

**Comment by horar** [comment]
this was connect button issues; and it looks like a duplicate to #137 - what was meantime fixed and will be released with v1.5.0
