### ISSUE TITLE
Connection "lost" (broken) after 10 mins

### ISSUE THREAD

**Issue by yexihu** [openconnect/openconnect-gui#143]
1.4.1 Openconnect.exe  windows7
When I use openconnect on the win7 to connect, I can Access YouTube.
However after  10 mins the connection breaks down (not access YouTube ).
But I use openconnect on the Ubuntu to connect, no such problem occurs.

[1.txt](https://github.com/openconnect/openconnect-gui/files/580126/1.txt)

**Comment by horar** [comment]
Hi @yexihu , you can try never version of openconnect console app (some pre-build binaries are here:
https://github.com/horar/openconnect/releases/tag/v7.07)

Last openconnect-gui release bundle openconnect 7.06; may be look to mailing list of openconnect project for faster response :-)

**Comment by yexihu** [comment]
Thanks for @horar ,I also try new version of openconnect console app （I use build_mingw-openconnect-w64@fedora25.sh to build new version of openconnect console app on Fedora 24 (MinGW)）,but he same problem exists.

**Comment by nmav** [comment]
Have you checked whether some other application or firewall changes your routing table?

**Comment by yexihu** [comment]
Thanks to @nmav ,I tyr to route print ,the reslut is here:
[route.txt](https://github.com/openconnect/openconnect-gui/files/582873/route.txt)

I also try to use  anyconnectto to connect, no such problem occurs.

**Comment by gky99** [comment]
I met that problem either. The internet is down whenever it get Send/Got CSTP DPD.
However, the client still shows that it's connected and continues to Get CSTP DPD respond and it's shown that the VPN client has internet connection in the "Network and Sharing Center".

**Comment by frunzales** [comment]
I'm experiencing the same issue with v1.4.0 and v1.4.1 clients.

**Comment by yexihu** [comment]
set REDIRECT_GATEWAY_METHOD=2 on vpnc-script.js,the problem was solved
