### ISSUE TITLE
Where is Usergroup password?

### ISSUE THREAD

**Issue by lopar** [openconnect/openconnect-gui#144]
Cannot specify usergroup password.
I even do not have such a field in program. 
I add usergroup name in address, but that's all I can do with usergroups.

**Comment by horar** [comment]
You will be prompted if the password is required.
Btw. could you please command line option to console openconnect.exe for this password type?

**Comment by horar** [comment]
Hi, did you manage to log in?

**Comment by lopar** [comment]
Hi, I stopped working with the company, who used Cisco VPN, so I cannot confirm is the problem solved or not, sorry.

**Comment by horar** [comment]
ok, thanks for update.
I'm closing this until someone will come back...
