### ISSUE TITLE
vpnc-script interface name resolving

### ISSUE THREAD

**Issue by tmandys** [openconnect/openconnect-gui#145]
### Description of the Issue

Network adapter for openconnect is created by Windows with name localized to local language (e.g. "Připojení k místní síti 9"). When such a string contains special characters then there is probably ANSI/DOS translation problem when looking for interface index by regex.

### Specifications
- **Version**: 1.4
- **Platform**: Windows 7 64-bit, Czech

### Prerequisites
* [x] Can you reproduce the problem?
* [x] Are you running the latest version?

### Steps to Reproduce the Issue

1. rename interface to use special national chars

### Expected Behavior

VPN connection to be established and traffic via VPN gateway

### Actual Behavior

I can see in log windows errors 1813 related to netsh command (Failed to spawn script "vpnc-script.js" connect:  The specified resource type cannot be found in the image file". VPNC is established but trafic is routing via default gateway. vpnc script does not resolves interface index correctly.

### Other Information

I'd echo to log script also TUNDEV and at least modify somehow getInterfaceId(ifname) to write an explaining text when interface is not found. Currently getInterfaceId(ifname) returns silently 0 as correct interface idx.

I solved it when I renamed interface in network manager to "Openconnect" but finding what's problem took plenty of time.

**Comment by dwmw2** [comment]
Hm, is this fixed by exporting the `TUNIDX` variable to the script?

**Comment by horar** [comment]
@dwmw2 using original script from upstream repo work fine for me; the actual vpnc script bundled with oc-gui fails for me too (with renamed device name as mentioned above).

As far I remember gui script has only 3 modification - logging stuff for GUI + banner (I will re-introduce it agains upstream version) and that TUNIDX feature

**Comment by dwmw2** [comment]
I'm not sure the TUNIDX bit got committed upstream, although I find it in the Samba share I was exporting to my Windows test box... back in the days when I had a Windows test box. Would be good to get that properly tested and merged.

**Comment by horar** [comment]
okey, I look closer that actual script; using interface name "Připojení k místní síti 9" from Win10 home (english windows with Slovak localization, chcp is 852);
- I can connect using openconnect --interface "Připojení k místní síti 9" HOST
- I can connect using upstream vpnc-script-win.js script via openconnect-gui

But our actual script try to use a function:
<pre>
function getInterfaceId(ifname) {
	var rx_ifid = new RegExp("^ *([0-9]+) *.*" + ifname + "$", "m")
	if (exec("netsh interface ip show interfaces").search(rx_ifid)) {
                echo("===========> IF: " + RegExp.$1);
		return (RegExp.$1);
	}
	return ("");
}
</pre>
what is the problem. I can see in log something like:
<pre>
2017-02-23 00:29:52 | 19d0 | <<-- [EXEC] netsh interface ip show interfaces
2017-02-23 00:29:52 | 19d0 | 
2017-02-23 00:29:52 | 19d0 | Idx     Met         MTU          State                Name
2017-02-23 00:29:52 | 19d0 | ---  ----------  ----------  ------------  ---------------------------
2017-02-23 00:29:52 | 19d0 |   1          75  4294967295  connected     Loopback Pseudo-Interface 1
2017-02-23 00:29:52 | 19d0 |   3          35        1500  connected     Ethernet
2017-02-23 00:29:52 | 19d0 |  12          25        1500  disconnected  Wi-Fi
2017-02-23 00:29:52 | 19d0 |  23          35        1200  connected     Pýipojenˇ k mˇstnˇ sˇti 9
2017-02-23 00:29:52 | 19d0 |   8          25        1500  connected     VirtualBox Host-Only Network #2
2017-02-23 00:29:52 | 19d0 |  11          25        1500  connected     VirtualBox Host-Only Network
2017-02-23 00:29:52 | 19d0 |   9          25        1500  connected     VirtualBox Host-Only Network #3
2017-02-23 00:29:52 | 19d0 | 
2017-02-23 00:29:52 | 19d0 | -->> (ret: 0)
</pre>

and the RegExp.$1 log msg return value 0 i.e. nothing found (yes, we should handle marginal cases). I can look to openconnect source code and check how is the script invoked, I see in output of 'cscript /?' there is a '/U' switch, may be it will help to get idx=23
Or we should use previous interface names in script similar to upstream version of script.
Will try and come back...

**Comment by dwmw2** [comment]
But isn't this why I fixed OpenConnect to pass the $TUNIDX variable into the script? So the script doesn't *need* to have a `getInterfaceId()` function at all?

**Comment by horar** [comment]
yes, when we have this variable, we should drop that function, there is no need to for duplicate the functionality...

**Comment by dwmw2** [comment]
It's in the 7.08 release...
