### ISSUE TITLE
Failed to write to TAP device The data area passed to a system call is too small 

### ISSUE THREAD

**Issue by shanecode** [openconnect/openconnect-gui#147]
Description of the Issue

When i connected the server use the openconnect-gui,I get this log:
"Failed to write to TAP device The data area passed to a system call is too small".

I think it is my ocserver server's problem, Because it is only happen in special server.
But I dont know how to make the server work.

I can give you the server ip , you can use openconnect-gui reduce the error.

Specifications

Version: openconnect-gui 1.4.1; ocserv server 0.11.3; TAP 9.21.2
Platform: windows 10 x64

**Comment by shanecode** [comment]
Nov 22 16:33:47 centos65-64-151230 ocserv[4011]: worker[huson]: 101.229.117.38 suggesting DPD of 90 secs
Nov 22 16:33:47 centos65-64-151230 ocserv[4011]: worker[huson]: 101.229.117.38 configured link MTU is 1500
Nov 22 16:33:47 centos65-64-151230 ocserv[4011]: worker[huson]: 101.229.117.38 peer's data MTU is 1406 / link is 1500
Nov 22 16:33:47 centos65-64-151230 ocserv[4011]: worker[huson]: 101.229.117.38 reducing MTU due to TCP MSS to 1387 (from 1500)
Nov 22 16:33:47 centos65-64-151230 ocserv[4011]: worker[huson]: 101.229.117.38 sending IPv4 192.168.8.75
Nov 22 16:33:47 centos65-64-151230 ocserv[4011]: worker[huson]: 101.229.117.38 adding DNS 114.114.114.114
Nov 22 16:33:47 centos65-64-151230 ocserv[4011]: worker[huson]: 101.229.117.38 Include route 10.10.10.0/255.255.255.0
Nov 22 16:33:47 centos65-64-151230 ocserv[4011]: worker[huson]: 101.229.117.38 Include route 192.168.0.0/255.255.0.0
Nov 22 16:33:47 centos65-64-151230 ocserv[4011]: worker[huson]: 101.229.117.38 Exclude route 192.168.5.0/255.255.255.0
Nov 22 16:33:47 centos65-64-151230 ocserv[4011]: worker[huson]: 101.229.117.38 DTLS ciphersuite: OC-DTLS1_2-AES128-GCM
Nov 22 16:33:47 centos65-64-151230 ocserv[4011]: worker[huson]: 101.229.117.38 DTLS data MTU 1321
Nov 22 16:33:47 centos65-64-151230 ocserv[4011]: worker[huson]: 101.229.117.38 Link MTU is 1387 bytes

**Comment by shanecode** [comment]
@horar could you help me please

**Comment by horar** [comment]
hi @shanecode , let's try:
1. a command line openconnect.exe (an optional part of openconnect.gui installer package, GUI is only wrapper over openconnect library)
2. you can try use never version of command line openconnect (or you can wait few weeks for next openconnect-gui release) - [here](https://github.com/horar/openconnect/releases/tag/v7.07)

**Comment by shanecode** [comment]
@horar 
The never version for opennconnect not work 
and cisco anyconnect work fine ...

**Comment by horar** [comment]
hi @shanecode 
Your logs indicate the MTU was changed, this sould be implemented in [v7.08](https://github.com/horar/openconnect/releases/tag/v7.08) ... this is not yet implemented, but will come into GUI in v1.6.x.

Could you please try v7.08 from above link and prove it solve your problem?
Thanks.

**Comment by shanecode** [comment]
@horar Thanks horar  I will try v7.08 and report

**Comment by shanecode** [comment]
@horar 7.08 not work  also ”Failed to write to TAP device The data area passed to a system call is too small”

**Comment by horar** [comment]
@shanecode I'm sorry, no idea what's wrong.
You should [ask openconnect team directly](http://www.infradead.org/openconnect/mail.html). it's upstream project for this GUI.

**Comment by itviewer** [comment]
I compiled the new code,but the problem still exists,why?

**Comment by horar** [comment]
@itviewer if it is not working, then problem is probablyin upstream openconnect project and not in GUI; this project is just a gui on top of openconnect library.

**Comment by itviewer** [comment]
@horar ok , I test with the openconnect command tool, same problem, seems it indeed cause by upstream
