### ISSUE TITLE
the .cat file and signature of tap-windows are expired.

### ISSUE THREAD

**Issue by shaellancelot** [openconnect/openconnect-gui#148]

**Comment by horar** [comment]
TAP drivers are from OpenVPN project. We are only re-using them.
I guess, you are facing problem mentioned in this issue: https://community.openvpn.net/openvpn/ticket/798

As soon as available, we can make a re-release with more actual version of TAP drivers from
https://openvpn.net/index.php/open-source/downloads.html

**Comment by horar** [comment]
There is nothing to do in openconnect-gui project. When new TAP drivers appears, then next release will include them. Closing this ticket for now.
