### ISSUE TITLE
"Disconnect" Issues

### ISSUE THREAD

**Issue by MarkLoukko** [openconnect/openconnect-gui#149]
Hi there,

First of all, great software, clean and simple. I really like it. :-)

I can connect to my VPN server without any issues. After 30 seconds to a minute any request I make no longer works, I just get a timeout error. Nothing appears in the log (see below). I can consistently reproduce it. Any ideas? Can I turn on some higher logging level? 

Cheers
Mark

Here are the last few lines of my log:
...
2016-12-22 22:26 Send CSTP DPD
2016-12-22 22:26 Got CSTP DPD response
2016-12-22 22:29 Send CSTP DPD
2016-12-22 22:29 Got CSTP DPD response
2016-12-22 22:30 Send CSTP DPD
2016-12-22 22:30 Got CSTP DPD response
Send CSTP DPD
Got CSTP DPD response
Send CSTP DPD
Got CSTP DPD response
Send CSTP DPD
Got CSTP DPD response
Send CSTP DPD
Got CSTP DPD response
Send CSTP DPD
Got CSTP DPD response
Send CSTP DPD
Got CSTP DPD response

**Comment by horar** [comment]
hi, is this reproducible with console client as well?

**Comment by MarkLoukko** [comment]
Hi there, 

Not sure... I'm a bit of a noob with OpenConnect. Where can I find some  examples  command lines?     

Cheers 
Mark 

----- Original Message -----

**Comment by horar** [comment]
when you make full installation of this GUI app, then go into your "Program file (x86)\openconnect-gui" folder, start command line console in admin mode (top menu, on Win10) and invoke "openconnect.exe <https://........>"

**Comment by widewing** [comment]
I'm experiencing exactly the same issue, also reproducible with the openconnect cli application. packages just jump back to original default link after about half a minute. And it's weird the "route print" shows VPN route still has the lowest metric...

**Comment by horar** [comment]
hi @widewing  if the problem exists with console application as well, we should initiate discussion with author of openconnect in [upstream project mailing list](http://lists.infradead.org/mailman/listinfo/openconnect-devel). GUI project is based on upstream openconnect library.
Closing here.
