### ISSUE TITLE
macOS binaries

### ISSUE THREAD

**Issue by jakepetroules** [openconnect/openconnect-gui#153]
Could you please begin providing pre-built binaries for macOS? I'd suggest building a Drag 'n' Drop DMG using Travis, that way if none of the developers of this project have access to a Mac, binaries can still be provided for users.

**Comment by horar** [comment]
This is the plan ,to share macOS drag&drop package similar to win32 NSIS installer package. At least until I have access to macOS. 
It's already ready, just way for 1.5 release (in near time).

But, feel free to create pull request for travis or gitlab YML file for macOS....

**Comment by horar** [comment]
Please find preview pacakge in v1.5.1 releaes
