### ISSUE TITLE
openconnect command line and password

### ISSUE THREAD

**Issue by samueleLucarini** [openconnect/openconnect-gui#155]
Hi, with version 7.07 of openconnect  from command line, 
I'm trying to enter the password as follows:

echo password|openconnect.exe -u test --passwd-on-stdin vpn.server.com
stdin read 6: 10084 2573
Password is '瀧獡睳牯❤਍'

what am I doing wrong ?
Thanks

**Comment by horar** [comment]
There is a problem while reading password from stdin on windows. Please see the discussion in #101

**Comment by samueleLucarini** [comment]
i've tried but i don't resolve..... someone has the last binary ? My OS is Windows 10 64.bit....

Thanks

**Comment by horar** [comment]
you can try e.g. this [unofficial windows build](https://github.com/horar/openconnect); just put vpnc.js script from upstream repository or copy-paste from installed openconnect-gui

**Comment by horar** [comment]
(you try openconnect from mentioned url; pls. follow the issue in #101 ticket)

**Comment by samueleLucarini** [comment]
i've download last version of openconnect (7.08)
I use this syntax :

1.  echo|set /p=test|openconnect.exe -u utente vpn.server
2.  echo|set /p=test|openconnect.exe -u utente --passwd-on-stdin vpn.server
3.  echo test|openconnect.exe -u utente --passwd-on-stdin vpn.server

In first case ask me password, in the second and in the third case after execute wait that user digit the password
where am I doing wrong ?

**Comment by horar** [comment]
If hints mentioned in that ticket doesn't work you, then it was not fixed yet.

'openconnect' is upstream proejct. This projest is GUI based on this project.
Probably you should talk directly to developers via http://www.infradead.org/openconnect/mail.html
