### ISSUE TITLE
MAC OSX Crash

### ISSUE THREAD

**Issue by priprd** [openconnect/openconnect-gui#160]
Hi the new build Darwin crash on Mac OSX Sierra after push button connect

Error log:
`
Process:               openconnect-gui [528]
Path:                  /Applications/openconnect-gui.app/Contents/MacOS/openconnect-gui
Identifier:            io.github.openconnect.openconnect-gui
Version:               ??? (1.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           openconnect-gui [528]
User ID:               0

Date/Time:             2017-02-14 09:11:42.253 +0100
OS Version:            Mac OS X 10.12.3 (16D32)
Report Version:        12
Anonymous UUID:        80980E28-3B83-8823-0BEF-DBFF8A5D3CC6

Time Awake Since Boot: 140 seconds

System Integrity Protection: enabled

Crashed Thread:        9  Thread (pooled)

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]
`

**Comment by horar** [comment]
Could you please:
1. did openconnect console app works for you?
1. upload the log files (/Users/$USER/Library/Application Support/OpenConnect-GUI Team/OpenConnect-GUI/logs/)
2. share information about your VPN (auth. type, protocol etc.)
3.  any other useful observation?
Thanks.

**Comment by priprd** [comment]
1) Before i Using console via Homebrew
2) `Openconnect-GUI` VPN client (1.5.1-dirty) logging started
     POST https://vpn.somewhere.net
3) Cisco anyconnect, auth username + password + group
4) I didnt have anythning else, have GUI develope mode or Debuger Mode?

**Comment by horar** [comment]
I can try make a debug build DMG and share a link with you on the weekend...  to gather more info.
Is it ok for you?

**Comment by priprd** [comment]
Yes absolutely no problem. thx

**Comment by wuzhongyi1105** [comment]
Ehhh, I also face the problem
Process:               openconnect-gui [9815]
Path:                  /Applications/openconnect-gui.app/Contents/MacOS/openconnect-gui
Identifier:            io.github.openconnect.openconnect-gui
Version:               ??? (1.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           openconnect-gui [9815]
User ID:               0

Date/Time:             2017-02-15 00:51:05.080 +0800
OS Version:            Mac OS X 10.12.4 (16E154a)
Report Version:        12
Anonymous UUID:        598C7402-375E-58E9-EC6A-94CC8DC022F5

Sleep/Wake UUID:       C3D082C0-1574-4DBC-BD95-BA3D2CD5D825

Time Awake Since Boot: 220000 seconds
Time Since Wake:       9000 seconds

System Integrity Protection: enabled

Crashed Thread:        8  Thread (pooled)

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

**Comment by horar** [comment]
ok, let try this:
1. do you see something in "sudo dmesg"?
2. let start the app from terminal and on admin-access-elevation, just 'Cancel' the dialog and accept info you won't be connected; now setup the profile & push connect - any difference in console or application log?
3. could you please try attached apps.? pls. both of them

[openconnect-gui-1.5.1-Darwin_rwdi.dmg.zip](https://github.com/openconnect/openconnect-gui/files/774895/openconnect-gui-1.5.1-Darwin_rwdi.dmg.zip)
[openconnect-gui-1.5.1-Darwin_rwdi-c2.dmg.zip](https://github.com/openconnect/openconnect-gui/files/774896/openconnect-gui-1.5.1-Darwin_rwdi-c2.dmg.zip)

**Comment by priprd** [comment]
Hi on Dmesg its only:

> AMFI: allowing exception handler for 'openconnect-gui' (486) becouse tis process is unsigned

but this message its only on dmesg twice but i run aplication moren then twenty 

starting via comand line with sudou and Cancel dialog about root privilegeies its same result witch same logs. 

Trying with all builds result its same

**Comment by horar** [comment]
Didn't you get more info in error log with attached applications?

Other reason could be that application is not signed.
May be you can try turn off the GateKeeper or add exception for this app [like described here](http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/)

**Comment by priprd** [comment]
Hi GateKeeper i Turn off, result same, application crash after push button connect. No news in logs.

**Comment by horar** [comment]
Do you get more info in crash error handler?

**Comment by priprd** [comment]
I didnt saw anything new
> Process:               openconnect-gui [618]
Path:                  /Applications/openconnect-gui.app/Contents/MacOS/openconnect-gui
Identifier:            io.github.openconnect.openconnect-gui
Version:               ??? (1.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           openconnect-gui [618]
User ID:               0

Date/Time:             2017-02-16 13:13:01.632 +0100
OS Version:            Mac OS X 10.12.3 (16D32)
Report Version:        12
Anonymous UUID:        80980E28-3B83-8823-0BEF-DBFF8A5D3CC6

Sleep/Wake UUID:       72802F4D-4983-49FE-A284-B23A9059FA53

Time Awake Since Boot: 1500 seconds
Time Since Wake:       30 seconds

System Integrity Protection: enabled

Crashed Thread:        9  Thread (pooled)

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

**Comment by horar** [comment]
I found an machine, where is the problem reproducible...

**Comment by horar** [comment]
Hi @priprd and @wuzhongyi1105 , I assemble new build; could you please try it?
Thanks in advance.
[openconnect-gui-1.5.1-Darwin.dmg.zip](https://github.com/openconnect/openconnect-gui/files/842615/openconnect-gui-1.5.1-Darwin.dmg.zip)

**Comment by priprd** [comment]
Hi @horar its work on Sierra, but the latest build on El Capition its have same problem.

**Comment by alimakki** [comment]
Also having a similar issue with El Capitan (v10.11.6).

Anything I can do to help?

**Comment by horar** [comment]
@alimakki I know the source of problem - homebrew is not a good source for package sharing...
You can compile from source code yourself and this should work fine.

**Comment by horar** [comment]
Hi, could someone please try this Homebrew package on macOS (sorry, HighSierra only) - https://github.com/horar/homebrew-openconnect-gui
Thanks.

**Comment by mikeybeck** [comment]
Hi @horar, I'm using HighSierra and Openconnect-gui suddenly stopped working for me, so I installed that package and it worked great, thanks!  
However, note that my problem was a bit different to that described in this thread; I couldn't get it to run at all.
Apologies if this isn't helpful for you.

**Comment by horar** [comment]
Looks like last test-package works, will be shipped with v1.5.3
