### ISSUE TITLE
The Windows built in VPN won‘t work

### ISSUE THREAD

**Issue by newgagabubu** [openconnect/openconnect-gui#164]
Hi, i installed the windows version of openconnect once, and found that error 720 kept occuring ever since, saying couldn't make connection to remote computer, when i tried to establish lt2p or ikev2 connections with the built in vpn. i'm not sure if it's the problem of the openconnect software, but other devices are ok with the same vpn account. is it possible that openconnect changed some system settings even though i already uninstalled it?

**Comment by horar** [comment]
Hi, I'm not aware about changes in mentioned system parts, but this project is just about GUI based on openconnect. 
If you need more info, you can ask author of openconnect in [more appropriate place](http://www.infradead.org/openconnect/mail.html)

**Comment by newgagabubu** [comment]
Right, thanks for reply!

**Comment by horar** [comment]
question moved to upstream mailing list; closing here
