### ISSUE TITLE
OpenConnect GUI v1.5.1 compatibility against Windows XP SP3

### ISSUE THREAD

**Issue by issacten** [openconnect/openconnect-gui#165]
It seems Windows XP is no longer compatible with latest version of OpenConnect GUI due to unsupported CancelIoEx function by Windows XP. My testing tells me that version 1.4.1 is the last working version in Windows XP.

Please consider adding the note in release note so that users would stay at version 1.4.1 for Windows XP, instead of spending effort on updating OpenConnect GUI.

**Comment by horar** [comment]
Yes, starting v1.5.0 is required Windows7 or newest. That OS is really old. I have no idea how many people still using openconnect-gui on that old system.
Anyway, I guess, the project could be compilable against Qt 5.6 LTS and should run on WindowsXP as well (I didn't try do this for longer time).

But release notes update with remark about changed minimum supported OS. Thank you for suggestion.
