### ISSUE TITLE
Windows 10 x64 not run openconnect-gui

### ISSUE THREAD

**Issue by suharik71** [openconnect/openconnect-gui#168]
Hello. I use Windows 10 x64/ When i run oppenconnect-gui give error.

Failed opening file C:/User/Антон/AppData/Local/OpenConnect-GUI Team/OpenConnect-GUI/logs/OpenConnect-GUI.txt
Version Openconnect-gui 1.5.1

I think the problem is in the path to the file. It contains spaces and Cyrillic characters

**Comment by horar** [comment]
hello, could u please tell us more?? It's not clear what 'run' mean in this scope. It's not clear what is the problem? The app can't start or can't connect? always or sometimes? Did you try bundled console client?? (if not, can you try it?).

I don't expect problems with spaces, but i can make a look to cyrilic or other non-us characters in path...
Thanks.

**Comment by ifenge** [comment]
I am Chinese,I have the same problem. My home pc  username is Chinese,So the installation directory contains Chinese. Error message: Failed opening file C:/User/张凌锋/AppData/Local/OpenConnect-GUI Team/OpenConnect-GUI/logs/OpenConnect-GUI.txt for writing: Invalid argument. My work pc username is English,OpenConnect-GUI use normal.

**Comment by AshrazRashid** [comment]
hi horar, i have a  problem on openconnect gui when batchmode is checked error is Authentication error; cannot obtain cookie. (win 10)(openconnect version v7.08)

**Comment by horar** [comment]
hi, @AshrazRashid, I don't think this is related to non-ascii string in path. From your description is not possible to identify the source of your problem.
