### ISSUE TITLE
How do I use the automatic login script?

### ISSUE THREAD

**Issue by GANHONG1995** [openconnect/openconnect-gui#169]
C:\Users\82237\Deskt
![qq 20170331074847](https://cloud.githubusercontent.com/assets/20258146/24530737/862a0d58-15e6-11e7-8612-95c8d194a9c9.png)
op\openvpn\openconnect.exe -u 822374242@qq.com -v us1.yunzhuan.com -p ghypp
Do i have to enter a password?
On windows
i use -p password

**Comment by horar** [comment]
yes, '-p' command line option is not for user password; it is for key password and similar.

You can either enter the password interactive (as you see above) or you can read them from stdin i.e. redirect via pipe (what is not working if you have non-english characters in password).

For more details, google for 'man openconnect'. This issues system is primary for openconnect-gui project.
Thanks
