### ISSUE TITLE
Retina support on macOS

### ISSUE THREAD

**Issue by netheril96** [openconnect/openconnect-gui#171]
### Description of the Issue

The current release of macOS client does not support retina screens. The fonts are all blurry. Given that Qt supports retina just fine, I don't think it will require much modifications for it to work on retina displays.

### Specifications
- **Version**: 1.5.1-dirty
- **Platform**: macOS Sierra 10.12.4 (64-bit)

### Prerequisites
* [x] Can you reproduce the problem?
* [x] Are you running the latest version?

**Comment by horar** [comment]
yes, HiDPI is not really supported yet in this app; but it's on todo list!

**Comment by netheril96** [comment]
@horar What is the obstacle? When I build a simple Qt app on macOS, I automatically get a retina-ready app. Is the complexity of openconnect-gui a problem?

**Comment by horar** [comment]
@netheril96 no, please check the Qt documentation for explanation related to macOS.
Anyway, it should be solved by eb5233e

**Comment by horar** [comment]
Just re-check devel version; looks ok on Retina.
