### ISSUE TITLE
McAfee Maleware Protection may block scripts from temp folder

### ISSUE THREAD

**Issue by th3ragex** [openconnect/openconnect-gui#174]
### Description of the Issue
It seems McAfee Maleware protection is blocking the execution of scripts from the temp folders. I am not quite sure which action was blocked and what are the missing results in the UI. I just found the log entry and though this can't be rigth.

McAfee LogEntry (somehow in german):
Würde durch Zugriffsschutzregel blockiert (Regel wird derzeit nicht erzwungen) 	C:\WINDOWS\SYSWOW64\CSCRIPT.EXE	C:\USERS\<x>\APPDATA\LOCAL\TEMP\VPNC.LOG	Maximaler Spyware-Schutz:Ausführen von Skripten aus dem TEMP-Ordner verhindern	Blockierte Aktion: Schreiben

Blocked file: C:\USERS\<x>\APPDATA\LOCAL\TEMP\VPNC.LOG
Blocked executable: C:\WINDOWS\SYSWOW64\CSCRIPT.EXE
Blocked action: write

### Specifications
- Version: 1.4.1
- Platform: Win10 x64 (1607) + McAfee Enterprise

### Steps to Reproduce the Issue
1. Connect / use OpenConnect

**Comment by horar** [comment]
hi, I don't know why it blocks writing access to temporary location.
The script write log messages into windows temporary folder i.e. cscript start vpn-script.js and this js file log some actions...

**Comment by th3ragex** [comment]
This issue does not seem to be a problem anymore.  Fixed works for me.
