### ISSUE TITLE
Failing to launch due to "No such file or directory"

### ISSUE THREAD

**Issue by LarsOevlisen** [openconnect/openconnect-gui#178]
### Description of the Issue
When launching OpenConnect 1.5.1 an error popup appears with the text:

"Failed opening file C:/Users/USERNAME/AppData/Local/OpenConnect-GUI Team/OpenConnect-GUI/logs/OpenConnect-GUI.txt for writing: No such file or directory"

This error is also apparent in version 1.5.0, but not in 1.4.1 (haven't tested earlier versions).

### Specifications
- **Version**: 1.5.1
- **Platform**: Windows 10 64-bit, English (Great Britain)

### Steps to Reproduce the Issue

1. Install OpenConnect 1.5.1 accepting default settings
2. Run Openconnect 1.5.1
3. Error

### Expected Behavior
OpenConnect launching successfully.

### Actual Behavior
OpenConnect never launches due to critical error.

### Other Information
The Windows 10 machine was formatted and reinstalled with all security patches installed as per 06/07/2017 0900.

EDIT: No problem installing and running OpenConnect 1.4.1. It seems that the error is introduced after this release.

**Comment by horar** [comment]
Does your user name contain some 'special/international' non-ascii characters? It could be similar problem like fixed with #168

**Comment by LarsOevlisen** [comment]
Yes, it is a similar problem as #168.

The name containts the special character "Ø".

You can close as related to the aforementioned issue.
