### ISSUE TITLE
Connection crash using Digital Certificate on Mac OS X 10.12.5

### ISSUE THREAD

**Issue by carlosromel** [openconnect/openconnect-gui#179]
### Description of the Issue
I was unable do connect with OpenConnect-GUI. Application just crash (report attached).

### Specifications
- **Version**: 1.5.1-dirty
- **Platform**: Mac OS X 10.12.5

### Steps to Reproduce the Issue
1. Open OpenConnect-GUI;
2. Inform VPN Server address (dns address);
3. Inform username;
4. Press connect button.

### Expected Behavior
VPN successfully established.

### Actual Behavior
OpenConnect-GUI crashes (crash reporte attached).

### Other Information
My VPN requires Digital Certificate.

[OpenConnectCrashReport.txt](https://github.com/openconnect/openconnect-gui/files/1136760/OpenConnectCrashReport.txt)
[MacBookProSystemReport.txt](https://github.com/openconnect/openconnect-gui/files/1136761/MacBookProSystemReport.txt)

**Comment by horar** [comment]
hi, could you please add some more info for us?
- which gnutls version is used; do you build it from source code/MacPorts/HomeBrew (source code brew or bottled package)?
- do you build the openconnect-gui on your machine or you make a package on other machine and install to your PC?

Thanks.

**Comment by carlosromel** [comment]
Hi.
I don't build from source, just download latest dmg file (openconnect-gui-1.5.1-Darwin.dmg) from https://github.com/openconnect/openconnect-gui/releases.

Talking about gnuTLS, I found some references from:

> **$ locate gnutls**
> /Applications/VLC.app/Contents/MacOS/plugins/libgnutls_plugin.dylib
> /Volumes/openconnect-gui-1.5.1-Darwin/openconnect-gui.app/Contents/MacOS/libgnutls.30.dylib
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb
> /usr/share/zsh/5.2/functions/_gnutls

Thanks in advance,

Carlos Romel

**Comment by horar** [comment]
Thanks for update. I meant the GnuTLS version from about... but doesn't matter now.
That release package has a bug (#160). It work only on specific configuration.
My plan is to make new release for macOS in August (I believe, I know how to make more system friendly build) ...
I'm closing this as duplicate to #160
