### ISSUE TITLE
openconnect gui Share the vpn network route information 

### ISSUE THREAD

**Issue by yesu0523** [openconnect/openconnect-gui#181]
### Specifications
- **Version**: 1.5.1
- **Platform**:  Microsoft Windows 7 旗舰版 

### Steps to Reproduce the Issue

1. Open OpenConnect-GUI;
2. Inform VPN Server address (dns address);
3. Inform username and save username or connect 
4.  disconnect vpn ,
5 . Enter other vpn addresses，and Inform username and save username or connect .
6 ,cat the log window  or   run  'route print'  of the  cmd
7 .I see vpn before the route network information 

### Expected Behavior
connect success 

### Actual Behavior
Inherited the vpn route information

### Other Information
I think vpn route should be set according to vpnserver vpn route initialization

**Comment by horar** [comment]
I think, this will be solved by #125 in next release v1.5.2

**Comment by horar** [comment]
hi, could you please try v1.5.2 if the problem is solved? thanks.

**Comment by yesu0523** [comment]
thank's , I know it , I'll try it .
