### ISSUE TITLE
Clarify the minimum macOS version

### ISSUE THREAD

**Issue by jakepetroules** [openconnect/openconnect-gui#182]
Please clarify the minimum macOS version for OpenConnect. The top-level CMake file sets it to 10.9, but there is no corresponding `LSMinimumSystemVersion` key set in the Info.plist. Normally in qmake you can retrieve the default minimum version via the `QMAKE_MACOSX_DEPLOYMENT_TARGET` variable, but I'm not sure of the equivalent in CMake.

Further, based on the Qt version in use (you seem to only require 5.6, but build the macOS packages with 5.8), your minimum macOS version cannot be lower than the following:

- Qt 5.6: macOS 10.7
- Qt 5.7: macOS 10.8
- Qt 5.8: macOS 10.9
- Qt 5.9: macOS 10.10
- Qt 5.10: macOS 10.11(?) (we haven't decided yet)

**Comment by horar** [comment]
AFAIK, CMake doesn't have support for something like this by hand. But I can do it myself on Info.plist generation... 
Side note about the version. Theoretically, you can make your private build against older version Qt but at this time is the GUI build agains latest one.

I will try to handle this with next releases.
