### ISSUE TITLE
Unable to open OpenConnect-GUI. Keeps crashing all of a sudden

### ISSUE THREAD

**Issue by dsp1589** [openconnect/openconnect-gui#189]
### Description of the Issue
Open connect gui app crashes in mac

- **Version**: 1.51
- **Platform**: macOs

### Steps to Reproduce the Issue

1. Open OpenConnect-GUI

### Expected Behavior
Openconnect should open

### Actual Behavior
App crashes

### Other Information
Screen shot attached , Stack log attached.
[OpenConnect-GUI.1.txt](https://github.com/openconnect/openconnect-gui/files/1199667/OpenConnect-GUI.1.txt)
[openconnect stack.txt](https://github.com/openconnect/openconnect-gui/files/1199673/openconnect.stack.txt)

<img width="646" alt="screen shot 2017-08-04 at 4 07 39 am" src="https://user-images.githubusercontent.com/1726017/28960066-2ba38056-78cb-11e7-860c-745b7b0266b7.png">
[openconnect stack.txt](https://github.com/openconnect/openconnect-gui/files/1199656/openconnect.stack.txt)

**Comment by horar** [comment]
I got feeling, this was already fixed and should be in develop branch;
OK, it's long time, I have to manage next macOS/Windows release, give me few days...

**Comment by dsp1589** [comment]
great. I found a workaround temp! deleting the *.txt files inside the log folder worked :)
 Thanks for this app

**Comment by horar** [comment]
> great. I found a workaround temp! deleting the *.txt files inside the log folder worked :)
Thanks for this app

thanks for update; ok, then this was fixed in develop branch; will be released soon. The problem is related to rights elevation & log-rotation (i.e. it may appears again)
