### ISSUE TITLE
Windows 10 - invalid routes

### ISSUE THREAD

**Issue by ensemblebd** [openconnect/openconnect-gui#190]
If anyone encounters an issue on a fresh Windows 10 install, where it connect but the routes are invalid in route table (destination network subnet unreachable). 

Can be fixed with this (apparently): 
http://www.winhelponline.com/blog/error-there-is-no-script-engine-for-file-extension-when-running-js-files/

As per running command line which indicates js files aren't runnable.

**Comment by horar** [comment]
hmm, may be check upstream openconnect project i.e. mailing list; this UI is build on top of them (incl. script).

**Comment by N0rm4n** [comment]
I installed fresh and original windows 10 professional ... But  after I have connected It seems to be all right but unfortunately the route configuration didn't add correctly and default gateway is empty ! well , check the log : 
`Ethernet adapter Ethernet 3:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : TAP-Windows Adapter V9
   Physical Address. . . . . . . . . : 00-FF-B3-(changed by myself)
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : (changed by myself)
   IPv4 Address. . . . . . . . . . . : 10.18.240.46(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   DNS Servers . . . . . . . . . . . : 8.8.8.8
   NetBIOS over Tcpip. . . . . . . . : Enabled`
Log file : 
`2017-08-13 21:21:11 | 2538 | Persistent Routes:
2017-08-13 21:21:11 | 2538 |   None
2017-08-13 21:21:11 | 2538 | -->> (exitCode: 0)
2017-08-13 21:21:11 | 2538 | Default Gateway:192.168.20.1
2017-08-13 21:21:11 | 2538 | VPN Gateway: **MyserverIP**
2017-08-13 21:21:11 | 2538 | Internal Address: 10.18.240.46
2017-08-13 21:21:11 | 2538 | Internal Netmask: 255.255.255.0
2017-08-13 21:21:11 | 2538 | Internal Gateway: 10.18.240.1
2017-08-13 21:21:11 | 2538 | Interface idx: "13" ("Ethernet 3")
2017-08-13 21:21:11 | 2538 | <<-- [EXEC] route add **(changed my ip)** mask 255.255.255.255 192.168.20.1
2017-08-13 21:21:11 | 2538 |  OK!
2017-08-13 21:21:11 | 2538 | -->> (exitCode: 0)
2017-08-13 21:21:11 | 2538 | MTU: 1311
2017-08-13 21:21:11 | 2538 | <<-- [EXEC] netsh interface ipv4 set subinterface "13" mtu=1311 store=active
2017-08-13 21:21:11 | 2538 | Ok.
2017-08-13 21:21:11 | 2538 | 
2017-08-13 21:21:11 | 2538 | -->> (exitCode: 0)
2017-08-13 21:21:11 | 2538 | Configuring "13" interface for Legacy IP...
2017-08-13 21:21:11 | 2538 | <<-- [EXEC] netsh interface ip set interface "13" metric=1
2017-08-13 21:21:11 | 2538 | Ok.
2017-08-13 21:21:11 | 2538 | 
2017-08-13 21:21:11 | 2538 | -->> (exitCode: 0)
2017-08-13 21:21:11 | 2538 | <<-- [EXEC] netsh interface ip set address "13" static 10.18.240.46 255.255.255.0
2017-08-13 21:21:11 | 2538 | 
2017-08-13 21:21:11 | 2538 | -->> (exitCode: 0)
2017-08-13 21:21:11 | 2538 | <<-- [EXEC] netsh interface ip add dns "13" 8.8.8.8 index=1
2017-08-13 21:21:11 | 2538 | The object is already in the list.
2017-08-13 21:21:11 | 2538 | 
2017-08-13 21:21:11 | 2538 | 
2017-08-13 21:21:11 | 2538 | -->> (exitCode: 1)
`
same problem about js file ?

**Comment by horar** [comment]
Do you have installed original Cisco Anyconnect?
Do you you last version of oc-gui? Which version of TAP drivers is installed?

**Comment by N0rm4n** [comment]
**First of all thanks for quick response .** 

I have Installed Original Cisco anyconnect version : 4.2.04018 
My oc-gui version is last one also installed TAP driver included and default settings : 1.5.2(32bit)
My TAP Driver version : TAP-Windows Adapter V9
My OS is windows : OS Name:  Microsoft Windows 10 Pro
OS Version: 10.0.15063 N/A Build 15063 (LAST UPDATED)

Also Detailed Information for TAP driver : 
TAP0901.SYS
 File Version : 9.0.0.21
Product Version : 9.21.2.9/21
If you need any other information just drop me a line . I am tracing problem and find only default gateway didnt add , DNS , IP , and also VPN handshaking happened ... 
Thanks for you time !

**Comment by horar** [comment]
Could you please try uninstall Cisco Anyconnect, OpenConnect-GUI and TAP drivers... (may be restart) and then install OpenConnect-GUI only?
I guess, someone reported connection troubles when using official and this free clients together.

**Comment by N0rm4n** [comment]
sure I have another workstation ! I have original cisco anyconnect on that too . I'll install oc-gui and If I have same problem Then Uninstall all of them cisco any orginal , tap drivers , oc-gui and reboot .... install fresh openconnect-gui and test it again !

**Comment by N0rm4n** [comment]
Ok ! on ther station (windows 64bit 10 pro) I have installed the same version of oc-gui , also I had cisco anyconnect from past ... well, I had same problem default gateway is empty after connection . as you said I uninstalled all , Cisco OpenConnect , OpenConnect-Gui , and TAP drivers ... reboot ... Install fresh oc-gui and config it and try again and same problem ... TAP driver get IP and DNS but default Gateway was empty :(

**Comment by horar** [comment]
Hmm, sorry, no more ideas from me :/
The only thing you can change is the 'REDIRECT_GATEWAY_METHOD' parameter in the vpnc script; if it won't help, you should probably look to upstream openconnect project (this project is just about GUI based on top of openconnect library), may be someone is already discussing this issue or the team will have more ideas ...

**Comment by PurePackets** [comment]
Dear Horar , 
two days ago @office one of my team member told me he had openconnect-gui on his workstation (win10pro) and everything works as fine ! well, I think to myself how it could possible ?! well, I start investigate to find why . well, I find his opngui is little old version . well, I have download all of version and start Install all of them one by one ... from 1.4 to last one ...  And find interesting thing ! Openconnect-gui ver 1.5.1 and before version working fine ! and everything is good! I told myself what's happen from 15.1 to 1.5.2 !? I don't know ! well, I think you are as main coder of this project know better and I hope this information could help u to resolve problem in next version . If you need any other information to troubleshoot problem tell me . thanks for your time

**Comment by PurePackets** [comment]
Also version 1.4.1 in my benchmark for testing stability, reliability and speed is working really better than 1.5 series . in 1.5 sometimes packets dies ..

**Comment by horar** [comment]
Hi 'PurePacket',

so many exclamation marks. You are right, I'm a mantainer of this GUI project at this time, it's just GUI on top of upstream openproject, include of few small changes...

Thanks for research. It's not so big change between v1.5.1 - v.1.5.2;
Let try give me some more info...
1. are you problems related to above discussion/logs?
2. did you face this regression for included console tool as well or only in GUI version?

About changes introduced in new version:
- newest openconnect library add support for dynamic MTU support; yes - it slowdown litte bit the connection; i.e. this may improved,
- the vpnc.js script was updated with some logging and international interface support ([actual repo](https://github.com/horar/vpnc-scripts) ); you can try original script from [upstream project](http://git.infradead.org/users/dwmw2/vpnc-scripts.git)

**Comment by wlxiong** [comment]
I got exactly the same problem after upgrading to v1.5.2 on Win 10. Replacing `vpnc-script.js` under installation folder with the one from v1.5.1 fixes the empty gateway problem.

**Comment by dstsmallbird** [comment]
@wlxiong is right! 
Use v1.5.1 instead. Maybe there are some change on v1.5.2.

**Comment by Croydon** [comment]
I can confirm that 1.5.**2** is NOT working on Windows 10
I can confirm that 1.5.**2** IS working on Windows 7
I can confirm that 1.5.**1** IS working on Windows 10

**Comment by jan-glx** [comment]
The [newest version of the `vpnc-script.js` script from upstream](http://git.infradead.org/users/dwmw2/vpnc-scripts.git/blob_plain/HEAD:/vpnc-script-win.js) works as well under windows 10 with openconnect-gui v1.5.2.

**Comment by horar** [comment]
Could you please change in the installed vpnc script the line ~33 i.e. 'var REDIRECT_GATEWAY_METHOD = -1;' and set '0' value what was default in previous version?
Thanks.

**Comment by jan-glx** [comment]
@horar , yes, changing `vpnc-script.js` of version v1.5.2 around line 30 as described fixes the issue as well:
````diff
if (env("REDIRECT_GATEWAY_METHOD")) {
	var REDIRECT_GATEWAY_METHOD = env("REDIRECT_GATEWAY_METHOD");
} else {
-	var REDIRECT_GATEWAY_METHOD = -1;
+	var REDIRECT_GATEWAY_METHOD = 0;
}
````

**Comment by horar** [comment]
great! :-) ... so I will change the value back; original plan is control this variable via GUI (but this is not yet implemented). Thanks again
