### ISSUE TITLE
vpnc-script not running

### ISSUE THREAD

**Issue by badbob001** [openconnect/openconnect-gui#193]
### Description of the Issue
vpnc-script.js does not appear to be launched when connecting. No related error is shown in the main log. %temp%\vpnc.log is not created, which implies that vpnc-script.js was not run. It was working for months and mysteriously stopped working recently.

### Specifications
1.5.1 and 1.5.2
Windows 7 64bit

### Other Information
How do I debug this? Can I run vpnc-script.js manually? When I run 'cscript vpnc-script.js'. it doesn't show any output.

**Comment by horar** [comment]
hi, hard say what happen, let try these steps:
0. what do you mean with "no related error"? show us...
1. did you change any access rights for the account?
2. do you use/install other VPN client (e.g. official AnyConnect)?
3. did you try uninstall openconnect-gui and tap driver (from control panel) - both! and install oc-gui again?
4. did you try console version of openconnect? (it's optional tool in oc-gui installer)
5. the script is invoked by openconnect library with some env. variables to set-up; but yes - you can start it in command line, just to see what happen (because it won't update network configuration)
6. the output is logged into file only when set environment variable 'LOG2FILE' (it is done by gui app), otherwise it write the log to output

**Comment by badbob001** [comment]
0. After login, the log seems to show it connected with errors, but there is no indication the script is run:
```
...
2017-08-14 17:23:05 | 1d1c | Detected MTU of 1290 bytes (was 1300)
2017-08-14 17:23:06 | 1d1c | Opened tun device Local Area Connection 4
2017-08-14 17:23:06 | 1d1c | TAP-Windows driver v9.21 (0)
2017-08-14 17:23:25 | 1d1c | Send CSTP Keepalive
2017-08-14 17:23:35 | 1d1c | Send DTLS DPD
2017-08-14 17:23:35 | 1d1c | Send CSTP DPD
2017-08-14 17:23:35 | 1d1c | Got CSTP DPD response
2017-08-14 17:23:35 | 1d1c | Got DTLS DPD response
```
1. Do you mean the local account or the remote vpn account. No changes to local account. No idea about remote vpn account.
2. I do have other vpn software installed like anyconnect and openvpn connect, but they have co-existed for a long time.
3. Tried uninstall / re-install of 1.5.2.
4. How do I use the console version? Is that the same as running 'openconnect.exe'? If I run 'openconnect.exe https://xxxxxxxxx', it connects and invokes vpnc-script.js, but it doesn't enable any of the env variables used by the script like 'reason' or 'log2file' so the script doesn't do anything.

So if I do this:
```
set reason=connect
set log2file=1
openconnect.exe https://xxxxxxxxx
```
Then I see vpnc.log get created, which starts with some '[EXEC] route print' stuff. But of course the script doesn't really work since many of the env variables are not set.

Is there a way to get all the env variables so I can set them manually and run the script manually?

**Comment by horar** [comment]
> set log2file=1
> openconnect.exe https://xxxxxxxxx

is sufficient to start, openconnect.exe will setup all variables/addresses from VPN server and the script will/should trigger required changes in networking...
The GUI is based on openconnect project/library i.e. this exe is perfectly capable to connect to VPN, just no GUI.

Silly question - did you start above 2 commands in standard command line aka cmd.exe "with admin rights"? (or in PowerShell)

**Comment by badbob001** [comment]
Yes, ran as Administrator Command Prompt titled window and not powershell. So it looks like openconnect.exe is NOT setting up the variables.

Added the wscript.echo line to before the switch:
```
WScript.echo("reason:" + env("reason"));
switch (env("reason")) {
case "pre-init":
```
And the output shows that env var reason is blank. So does this mean it's an openconnect issue and not an openconnect-gui issue? I run 'set' and don't see any new env vars, though I don't know the scope of these env vars.
```
D:\Program Files (x86)\OpenConnect-GUI>openconnect.exe https://xxxxxxxxxxxxxxxxxxx
POST https://xxxxxxxxxxxxxxxxxxx/
 Connected to xxxxxxxxxxxxxxxxxxx
 SSL negotiation with xxxxxxxxxxxxxxxxxxx
 Connected to HTTPS on xxxxxxxxxxxxxxxxxxx
 Got HTTP response: HTTP/xxxxxxxxxxxxxxxxxxx.0 302 Temporary moved
 POST https://xxxxxxxxxxxxxxxxxxx/
 Connected to xxxxxxxxxxxxxxxxxxx
 SSL negotiation with xxxxxxxxxxxxxxxxxxx
 Connected to HTTPS on xxxxxxxxxxxxxxxxxxx
 Got HTTP response: HTTP/xxxxxxxxxxxxxxxxxxx.0 302 Temporary moved
 GET https://xxxxxxxxxxxxxxxxxxx/
 Connected to xxxxxxxxxxxxxxxxxxx
 SSL negotiation with xxxxxxxxxxxxxxxxxxx
 Connected to HTTPS on xxxxxxxxxxxxxxxxxxx
 Got HTTP response: HTTP/xxxxxxxxxxxxxxxxxxx.0 302 Temporary moved
 GET https://xxxxxxxxxxxxxxxxxxx/
 Connected to xxxxxxxxxxxxxxxxxxx
 SSL negotiation with xxxxxxxxxxxxxxxxxxx
 Connected to HTTPS on xxxxxxxxxxxxxxxxxxx
 Got HTTP response: HTTP/xxxxxxxxxxxxxxxxxxx.0 302 Temporary moved
 GET https://xxxxxxxxxxxxxxxxxxx/+webvpn+/index.html
 SSL negotiation with xxxxxxxxxxxxxxxxxxx
 Connected to HTTPS on xxxxxxxxxxxxxxxxxxx
 Welcome to xxxxxxxxxxxxxxxxxxx connection in xxxxxxxxxxxxxxxxxxx. This is a property of 
 xxxxxxxxxxxxxxxxxxx and is intended for business purpose only. 

 Due to virus threats, you must ensure that your PC is running up-to-date virus 
 protection. Contact the Service Desk at xxxxxxxxxxxxxxxxxxx if you need assistance. 

 xxxxxxxxxxxxxxxxxxx reserves the right to monitor its use as and when necessary to ensure 
 security, availability, and integrity of the systems. Unauthorized access is strictly 
 prohibited and shall be subject to disciplinary actions or prosecution. 

 Please enter your username and password.
 Username: xxxxxxxxxxxxxxxxxxx
 Password:
 POST https://xxxxxxxxxxxxxxxxxxx/+webvpn+/index.html
 Got CONNECT response: HTTP/xxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxx 200 OK
 CSTP connected. DPD 30, Keepalive 20
 Connected as xxxxxxxxxxxxxxxxxxx0.xxxxxxxxxxxxxxxxxxx47.84.7, using SSL
 Established DTLS connection (using GnuTLS). Ciphersuite (DTLS0.9)-(DHE-RSA-4294967237)
 -(AES-xxxxxxxxxxxxxxxxxxx28-CBC)-(SHAxxxxxxxxxxxxxxxxxxx).
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (xxxxxxxxxxxxxxxxxxx300 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (xxxxxxxxxxxxxxxxxxx299 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (xxxxxxxxxxxxxxxxxxx298 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (xxxxxxxxxxxxxxxxxxx297 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (xxxxxxxxxxxxxxxxxxx296 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (xxxxxxxxxxxxxxxxxxx295 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (xxxxxxxxxxxxxxxxxxx294 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (xxxxxxxxxxxxxxxxxxx293 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (xxxxxxxxxxxxxxxxxxx292 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (xxxxxxxxxxxxxxxxxxx29xxxxxxxxxxxxxxxxxxx -5)
 Detected MTU of xxxxxxxxxxxxxxxxxxx290 bytes (was xxxxxxxxxxxxxxxxxxx300)
 Microsoft (R) Windows Script Host Version 5.8
Copyright (C) Microsoft Corporation. All rights reserved.

reason:
Microsoft (R) Windows Script Host Version 5.8
Copyright (C) Microsoft Corporation. All rights reserved.

reason:
^C
D:\Program Files (x86)\OpenConnect-GUI>
```

**Comment by badbob001** [comment]
My guess is that the script is being run, but the env vars are not being set and so the switch statement is not triggered. I tried a 'exec("set")' in the script to see what variables are there and it came back blank, but maybe I'm doing it wrong.

How can I set these variables manually? Does the default logging provide all the values I would need?

**Comment by horar** [comment]
my output, the problematic part from your output is like:
>  Detected MTU of 1194 bytes (was 1200)
>  Microsoft (R) Windows Script Host verzia 5.812
> Copyright (C) Microsoft Corporation. Všetky práva vyhradené.
> 
> Microsoft (R) Windows Script Host verzia 5.812
> Copyright (C) Microsoft Corporation. Všetky práva vyhradené.
>
> <<-- [EXEC] route print
> ===========================================================================
> Interface List
> .......

Everything else looks OK for me.

Do you have some antivirus/malware protection?

When you don't set 'set log2file=1' variable, the openconnect.exe should write log messages to console instead of log file in temporary folder. Could you pls. try this?

**Comment by badbob001** [comment]
My system does have symantec enterprise virus protection for years, but I didn't see anything in the logs. And I can't easily disable it.  I don't think I even enabled log2file in my testing. The console output ends with this:
```
 Got CONNECT response: HTTP/1.1 200 OK
 CSTP connected. DPD 30, Keepalive 20
 Connected as 10.147.235.104, using SSL
 Established DTLS connection (using GnuTLS). Ciphersuite (DTLS0.9)-(DHE-RSA-4294967237)-(AES-128-CBC)-(SHA1).
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1300 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1299 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1298 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1297 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1296 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1295 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1294 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1293 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1292 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1291 -5)
 Detected MTU of 1290 bytes (was 1300)
 Microsoft (R) Windows Script Host Version 5.8
Copyright (C) Microsoft Corporation. All rights reserved.

Microsoft (R) Windows Script Host Version 5.8
Copyright (C) Microsoft Corporation. All rights reserved.

^C
C:\Program Files (x86)\OpenConnect-GUI>set log2file
Environment variable log2file not defined

C:\Program Files (x86)\OpenConnect-GUI>
```
Are the env vars set by openconnect.exe or the tap-windows driver? As a workaround, I run a batch script after connecting which reads the ip information from the OpenConnect-GUI log to recreate the missing env vars and then run vpnc-script.js. It'll probably be easier if I can rewrite it in javascript so I can have it invoked automatically.


```
@echo off
echo ************* pre-vpnc start *************

set reason=%~1
if "%reason%"=="" echo ERROR: Syntax: pre-vpnc.bat [connect^|disconnect].& goto:EOF

set TUNDEV=
set TUNIDX=
for /f "tokens=1-4 delims=," %%a in ('wmic nic get name^,netconnectionid^,InterfaceIndex /format:csv ^| find "TAP-Windows"') do set TUNDEV=%%d& set TUNIDX=%%b
echo TUNDEV: %TUNDEV%
echo TUNIDX: %TUNIDX%

if "%TUNDEV%"=="" echo ERROR: Unable to get adapter name (TUNDEV).& goto:EOF
if "%TUNIDX%"=="" echo ERROR: Unable to get adapter idx (TUNIDX).& goto:EOF

goto:%reason%
goto:EOF


:connect
echo reason: %reason%
set logfile=%localappdata%\OpenConnect-GUI Team\OpenConnect-GUI\logs\OpenConnect-GUI
if not exist "%logfile%" echo ERROR: OpenConnect-GUI Log not found.& goto:EOF

set INTERNAL_IP4_MTU=
for /f "tokens=1-9" %%a in ('type "%logfile%" ^| find "Detected MTU of"') do set INTERNAL_IP4_MTU=%%i
if "%INTERNAL_IP4_MTU%"=="" echo ERROR: Unable to determine INTERNAL_IP4_MTU.& goto:EOF
echo INTERNAL_IP4_MTU: %INTERNAL_IP4_MTU%

set INTERNAL_IP4_ADDRESS=
for /f "tokens=1-7" %%a in ('type "%logfile%" ^| find "X-CSTP-Address:"') do set INTERNAL_IP4_ADDRESS=%%g
if "%INTERNAL_IP4_ADDRESS%"=="" echo ERROR: Unable to determine INTERNAL_IP4_ADDRESS.& goto:EOF
echo INTERNAL_IP4_ADDRESS: %INTERNAL_IP4_ADDRESS%

set INTERNAL_IP4_NETMASK=
for /f "tokens=1-7" %%a in ('type "%logfile%" ^| find "X-CSTP-Netmask:"') do set INTERNAL_IP4_NETMASK=%%g
if "%INTERNAL_IP4_NETMASK%"=="" echo ERROR: Unable to determine INTERNAL_IP4_NETMASK.& goto:EOF
echo INTERNAL_IP4_NETMASK: %INTERNAL_IP4_NETMASK%

set DNS2=
set DNS2POSITION=
for /f "tokens=1-8 delims=[] " %%a in ('type "%logfile%" ^| find/n "X-CSTP-DNS:"') do set DNS2POSITION=%%a& set DNS2=%%h
if "%DNS2%"=="" echo ERROR: Unable to determine DNS2.& goto:EOF
echo DNS2: %DNS2%

set DNS1=
for /f "tokens=1-7" %%a in ('type "%logfile%" ^| find/n "X-CSTP-DNS:" ^| find/v "[%DNS2POSITION%]"') do set DNS1=%%g
if "%DNS1%"=="" echo ERROR: Unable to determine DNS1.& goto:EOF
echo DNS1: %DNS1%

set INTERNAL_IP4_DNS=%DNS1% %DNS2% 8.8.8.8 8.8.4.4
echo INTERNAL_IP4_DNS: %INTERNAL_IP4_DNS%

goto:END

:setciscosplitvars
set /a INC=0
call:setip add 10.0.0.0 255.0.0.0 8
call:setip add 172.16.0.0 255.240.0.0 12
goto:EOF

:setip
set CMD=%~1
set ADDR=%~2
set MASK=%~3
set MASKLEN=%~4
set /a INC=%INC% + 1
set CISCO_SPLIT_INC=%INC%
set CISCO_SPLIT_INC_%INC%_ADDR=%ADDR%
set CISCO_SPLIT_INC_%INC%_MASK=%MASK%
set CISCO_SPLIT_INC_%INC%_MASKLEN=%MASKLEN%
goto:EOF


:disconnect
echo reason: %reason%
netsh interface ip set address "%TUNDEV%" dhcp
netsh interface ip set dns "%TUNDEV%" dhcp
goto:END

:END
call:setciscosplitvars
cscript vpnc-script.js
echo ************* pre-vpnc end *************
```

**Comment by horar** [comment]
> Are the env vars set by openconnect.exe or the tap-windows driver?

openconnect.exe tool set the environment variables and then it invokes JS script to update the netowrking thingy...
The log is used just for GUIrunning on top of openconnect library to gather details and inform the user what happens...

**Comment by horar** [comment]
Threre was one issue in vpnc script (fxed in #190). It the problem will exists in next release 1.5.3 (planned in this Month), feel free to reopen this issue...
