### ISSUE TITLE
After installing the GUI in Windows 10 ...

### ISSUE THREAD

**Issue by jeffd2651** [openconnect/openconnect-gui#195]
### Description of the Issue
After installation of the GUI into Windows 10 (64bit) I have been able to setup a profile and successfully get it to connect to my vpn. However, when I open a browser, it continues to report my current IP address and not the IP of the vpn.
I'm struggling to understand how I can this vpn to work in Windows 10

### Specifications
- **Version 1.5.2 (32 bit)**: 
- **Platform Windows 10 (64 bit Home edition)**: 

### Steps to Reproduce the Issue

1. Download the gui 
2. install with admin privileges 
3. setup the profile and connect

### Expected Behavior
 Expected the vpn to divert my connection to the vpn's IP address

### Actual Behavior
Well, apart from the GUI showing that the VPN is active and connected, nothing :(

### Other Information
Works great on my mobile phone (Android)

**Comment by jeffd2651** [comment]
There is a bug in the newest version v 1.5.2 ... if you revert to one of the previous version (I have gone back to v1.5.1) then it works perfectly.
I suggest that you investigate this ASAP ;)

**Comment by jeffd2651** [comment]
If a tunnel log reads that it can't resolve an address it is either an incorrect server address or firewall issue.  If the log reads that it can't authenticate it is incorrect credentials, possibly even certs but if a tunnel connects without errors but doesn't tunnel correctly you can bet your life it is not applying the correct route.

**Comment by horar** [comment]
@jeffd2651 hi, can you share logs from v1.5.1 and 1.5.2?? Thanks.

**Comment by jeffd2651** [comment]
I have downgraded to previous version so there is definitely a bug in the new version

**Comment by horar** [comment]
yes, let's try to find out what's wrong.
I'm using these releases, and I tried it on clean Windows agains Cisco server and everything work smooth for me.
So I will appriciate any kind of information what may help to solve your problem :-)

**Comment by jeffd2651** [comment]
Thank you for your email,
Like I said in my previous message ... after downgrading to the previous 
version it works OK (I'm running windows 10 fully updated) and as it's 
working OK, I'm sorry but I simply don't have the time to start 
reinstalling and then logging and then reverting back and logging etc 
etc).
I've spoken with a couple of other people and they too find the latest 
version doesn't work ... so it's not just me.
I appreciate the time you have taken to respond and I do appreciate the 
work you do but I honestly just don't have the time to spare. Sorry

Regards,
Jeff Dandy

------ Original Message ------

**Comment by ultimate-tester** [comment]
I vote to reopen this issue as I'm experiencing this problem as we speak. 
Here is the log of version 1.5.2:

> 2018-02-14 09:32:25 | 1464 | POST https://*************/
> 2018-02-14 09:32:25 | 1464 | Attempting to connect to server*************:443
> 2018-02-14 09:32:25 | 1464 | Connected to *************:443
> 2018-02-14 09:32:25 | 1464 | There was a non-CA certificate in the trusted list: OU=Copyright (c) 1997 Microsoft Corp.,OU=Microsoft Corporation,CN=Microsoft Root Authority.
> 2018-02-14 09:32:25 | 1464 | There was a non-CA certificate in the trusted list: C=US,O=MSFT,CN=Microsoft Authenticode(tm) Root Authority.
> 2018-02-14 09:32:25 | 1464 | There was a non-CA certificate in the trusted list: CN=Root Agency.
> 2018-02-14 09:32:25 | 1464 | SSL negotiation with *************
> 2018-02-14 09:32:25 | 1464 | Connected to HTTPS on *************
> 2018-02-14 09:32:25 | 1464 | Got HTTP response: HTTP/1.1 200 OK
> 2018-02-14 09:32:25 | 1464 | Content-Type: text/html; charset=utf-8
> 2018-02-14 09:32:25 | 1464 | Transfer-Encoding: chunked
> 2018-02-14 09:32:25 | 1464 | Cache-Control: no-cache
> 2018-02-14 09:32:25 | 1464 | Pragma: no-cache
> 2018-02-14 09:32:25 | 1464 | Connection: Keep-Alive
> 2018-02-14 09:32:25 | 1464 | Date: Wed, 14 Feb 2018 08:32:28 GMT
> 2018-02-14 09:32:25 | 1464 | X-Frame-Options: SAMEORIGIN
> 2018-02-14 09:32:25 | 1464 | X-Aggregate-Auth: 1
> 2018-02-14 09:32:25 | 1464 | HTTP body chunked (-2)
> 2018-02-14 09:32:25 | 1464 | XML POST enabled
> 2018-02-14 09:32:25 | 1464 | Please enter your username and password.
> 2018-02-14 09:32:25 | 1464 | POST https://*************/
> 2018-02-14 09:32:25 | 1464 | Got HTTP response: HTTP/1.1 200 OK
> 2018-02-14 09:32:25 | 1464 | Content-Type: text/html; charset=utf-8
> 2018-02-14 09:32:25 | 1464 | Transfer-Encoding: chunked
> 2018-02-14 09:32:25 | 1464 | Cache-Control: no-cache
> 2018-02-14 09:32:25 | 1464 | Pragma: no-cache
> 2018-02-14 09:32:25 | 1464 | Connection: Keep-Alive
> 2018-02-14 09:32:25 | 1464 | Date: Wed, 14 Feb 2018 08:32:28 GMT
> 2018-02-14 09:32:25 | 1464 | X-Frame-Options: SAMEORIGIN
> 2018-02-14 09:32:25 | 1464 | X-Aggregate-Auth: 1
> 2018-02-14 09:32:25 | 1464 | HTTP body chunked (-2)
> 2018-02-14 09:32:25 | 1464 | XML POST enabled
> 2018-02-14 09:32:25 | 1464 | Please enter your username and password.
> 2018-02-14 09:32:25 | 1464 | Select form: group_list
> 2018-02-14 09:32:25 | 1464 | Text form: username
> 2018-02-14 09:32:25 | 1464 | Password form: password
> 2018-02-14 09:32:25 | 1464 | Authentication failed in batch mode, retrying with batch mode disabled
> 2018-02-14 09:32:25 | 1464 | POST https://*************/
> 2018-02-14 09:32:25 | 1464 | Attempting to connect to server *************:443
> 2018-02-14 09:32:25 | 1464 | Connected to *************:443
> 2018-02-14 09:32:25 | 1464 | SSL negotiation with *************
> 2018-02-14 09:32:26 | 1464 | Connected to HTTPS on *************
> 2018-02-14 09:32:26 | 1464 | Got HTTP response: HTTP/1.1 200 OK
> 2018-02-14 09:32:26 | 1464 | Content-Type: text/html; charset=utf-8
> 2018-02-14 09:32:26 | 1464 | Transfer-Encoding: chunked
> 2018-02-14 09:32:26 | 1464 | Cache-Control: no-cache
> 2018-02-14 09:32:26 | 1464 | Pragma: no-cache
> 2018-02-14 09:32:26 | 1464 | Connection: Keep-Alive
> 2018-02-14 09:32:26 | 1464 | Date: Wed, 14 Feb 2018 08:32:28 GMT
> 2018-02-14 09:32:26 | 1464 | X-Frame-Options: SAMEORIGIN
> 2018-02-14 09:32:26 | 1464 | X-Aggregate-Auth: 1
> 2018-02-14 09:32:26 | 1464 | HTTP body chunked (-2)
> 2018-02-14 09:32:26 | 1464 | XML POST enabled
> 2018-02-14 09:32:26 | 1464 | Please enter your username and password.
> 2018-02-14 09:32:26 | 1464 | POST https://*************/
> 2018-02-14 09:32:26 | 1464 | Got HTTP response: HTTP/1.1 200 OK
> 2018-02-14 09:32:26 | 1464 | Content-Type: text/html; charset=utf-8
> 2018-02-14 09:32:26 | 1464 | Transfer-Encoding: chunked
> 2018-02-14 09:32:26 | 1464 | Cache-Control: no-cache
> 2018-02-14 09:32:26 | 1464 | Pragma: no-cache
> 2018-02-14 09:32:26 | 1464 | Connection: Keep-Alive
> 2018-02-14 09:32:26 | 1464 | Date: Wed, 14 Feb 2018 08:32:28 GMT
> 2018-02-14 09:32:26 | 1464 | X-Frame-Options: SAMEORIGIN
> 2018-02-14 09:32:26 | 1464 | X-Aggregate-Auth: 1
> 2018-02-14 09:32:26 | 1464 | HTTP body chunked (-2)
> 2018-02-14 09:32:26 | 1464 | XML POST enabled
> 2018-02-14 09:32:26 | 1464 | Please enter your username and password.
> 2018-02-14 09:32:26 | 1464 | Select form: group_list
> 2018-02-14 09:32:26 | 1464 | Text form: username
> 2018-02-14 09:32:26 | 1464 | Password form: password
> 2018-02-14 09:32:29 | 1464 | POST https://*************/
> 2018-02-14 09:32:29 | 1464 | Got HTTP response: HTTP/1.1 200 OK
> 2018-02-14 09:32:29 | 1464 | Content-Type: text/html; charset=utf-8
> 2018-02-14 09:32:29 | 1464 | Transfer-Encoding: chunked
> 2018-02-14 09:32:29 | 1464 | Cache-Control: no-cache
> 2018-02-14 09:32:29 | 1464 | Pragma: no-cache
> 2018-02-14 09:32:29 | 1464 | Connection: Keep-Alive
> 2018-02-14 09:32:29 | 1464 | Date: Wed, 14 Feb 2018 08:32:31 GMT
> 2018-02-14 09:32:29 | 1464 | X-Frame-Options: SAMEORIGIN
> 2018-02-14 09:32:29 | 1464 | X-Aggregate-Auth: 1
> 2018-02-14 09:32:29 | 1464 | HTTP body chunked (-2)
> 2018-02-14 09:32:29 | 1464 | Got CONNECT response: HTTP/1.1 200 OK
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Version: 1
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Protocol: Copyright (c) 2004 Cisco Systems, Inc.
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Address: 10.40.10.125
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Netmask: 255.255.224.0
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Hostname: *************
> 2018-02-14 09:32:29 | 1464 | X-CSTP-DNS: 10.19.32.24
> 2018-02-14 09:32:29 | 1464 | X-CSTP-DNS: 10.176.10.14
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Lease-Duration: 1209600
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Session-Timeout: none
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Idle-Timeout: 1800
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Disconnected-Timeout: 1800
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Default-Domain: *************
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Keep: true
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Tunnel-All-DNS: false
> 2018-02-14 09:32:29 | 1464 | X-CSTP-DPD: 30
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Keepalive: 20
> 2018-02-14 09:32:29 | 1464 | X-CSTP-MSIE-Proxy-Lockdown: true
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Smartcard-Removal-Disconnect: true
> 2018-02-14 09:32:29 | 1464 | X-DTLS-Session-ID: D1E7E172CADC810CA78CB256ABB314698A420C2C77A12CDBD87B43FE364947C8
> 2018-02-14 09:32:29 | 1464 | X-DTLS-Port: 443
> 2018-02-14 09:32:29 | 1464 | X-DTLS-Keepalive: 20
> 2018-02-14 09:32:29 | 1464 | X-DTLS-DPD: 30
> 2018-02-14 09:32:29 | 1464 | X-CSTP-MTU: 1300
> 2018-02-14 09:32:29 | 1464 | X-DTLS-MTU: 1300
> 2018-02-14 09:32:29 | 1464 | X-DTLS-CipherSuite: DHE-RSA-AES256-SHA
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Routing-Filtering-Ignore: false
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Quarantine: false
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Disable-Always-On-VPN: false
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Client-Bypass-Protocol: false
> 2018-02-14 09:32:29 | 1464 | X-CSTP-TCP-Keepalive: true
> 2018-02-14 09:32:29 | 1464 | X-CSTP-Post-Auth-XML: <elided>
> 2018-02-14 09:32:29 | 1464 | CSTP connected. DPD 30, Keepalive 20
> 2018-02-14 09:32:29 | 1464 | CSTP Ciphersuite: (TLS1.0)-(DHE-RSA-1024)-(AES-256-CBC)-(SHA1)
> 2018-02-14 09:32:29 | 1464 | Opened tun device Ethernet 2
> 2018-02-14 09:32:29 | 1464 | TAP-Windows driver v9.21 (0)
> 2018-02-14 09:32:29 | 1464 | <<-- [EXEC] route print
> 2018-02-14 09:32:29 | 1464 | ===========================================================================
> 2018-02-14 09:32:29 | 1464 | Interface List
> 2018-02-14 09:32:29 | 1464 |  22...00 ff 1c c3 22 ea ......TAP-Windows Adapter V9
> 2018-02-14 09:32:29 | 1464 |   3...f4 6d 04 ec ff b0 ......Realtek PCIe GBE Family Controller
> 2018-02-14 09:32:29 | 1464 |   1...........................Software Loopback Interface 1
> 2018-02-14 09:32:29 | 1464 |   2...00 00 00 00 00 00 00 e0 Teredo Tunneling Pseudo-Interface
> 2018-02-14 09:32:29 | 1464 | ===========================================================================
> 2018-02-14 09:32:29 | 1464 | 
> 2018-02-14 09:32:29 | 1464 | IPv4 Route Table
> 2018-02-14 09:32:29 | 1464 | ===========================================================================
> 2018-02-14 09:32:29 | 1464 | Active Routes:
> 2018-02-14 09:32:29 | 1464 | Network Destination        Netmask          Gateway       Interface  Metric
> 2018-02-14 09:32:29 | 1464 |           0.0.0.0          0.0.0.0    192.168.2.254      192.168.2.9     26
> 2018-02-14 09:32:29 | 1464 |         127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
> 2018-02-14 09:32:29 | 1464 |         127.0.0.1  255.255.255.255         On-link         127.0.0.1    331
> 2018-02-14 09:32:29 | 1464 |   127.255.255.255  255.255.255.255         On-link         127.0.0.1    331
> 2018-02-14 09:32:29 | 1464 |       192.168.2.0    255.255.255.0         On-link       192.168.2.9    281
> 2018-02-14 09:32:29 | 1464 |       192.168.2.9  255.255.255.255         On-link       192.168.2.9    281
> 2018-02-14 09:32:29 | 1464 |     192.168.2.255  255.255.255.255         On-link       192.168.2.9    281
> 2018-02-14 09:32:29 | 1464 |         224.0.0.0        240.0.0.0         On-link         127.0.0.1    331
> 2018-02-14 09:32:29 | 1464 |         224.0.0.0        240.0.0.0         On-link                16    257
> 2018-02-14 09:32:29 | 1464 |         224.0.0.0        240.0.0.0         On-link       192.168.2.9    281
> 2018-02-14 09:32:29 | 1464 |   255.255.255.255  255.255.255.255         On-link         127.0.0.1    331
> 2018-02-14 09:32:29 | 1464 |   255.255.255.255  255.255.255.255         On-link                16    257
> 2018-02-14 09:32:29 | 1464 |   255.255.255.255  255.255.255.255         On-link       192.168.2.9    281
> 2018-02-14 09:32:29 | 1464 | ===========================================================================
> 2018-02-14 09:32:29 | 1464 | Persistent Routes:
> 2018-02-14 09:32:29 | 1464 |   None
> 2018-02-14 09:32:29 | 1464 | 
> 2018-02-14 09:32:29 | 1464 | IPv6 Route Table
> 2018-02-14 09:32:29 | 1464 | ===========================================================================
> 2018-02-14 09:32:29 | 1464 | Active Routes:
> 2018-02-14 09:32:29 | 1464 |  If Metric Network Destination      Gateway
> 2018-02-14 09:32:29 | 1464 |   3    281 ::/0                     fe80::24a:77ff:fe5b:986
> 2018-02-14 09:32:29 | 1464 |   1    331 ::1/128                  On-link
> 2018-02-14 09:32:29 | 1464 |   2    331 2001::/32                On-link
> 2018-02-14 09:32:29 | 1464 |   2    331 2001:0:9d38:90d7:28bc:630:3f57:fdf6/128
> 2018-02-14 09:32:29 | 1464 |                                     On-link
> 2018-02-14 09:32:29 | 1464 |   3    281 2a02:a445:6a86:1::/64    On-link
> 2018-02-14 09:32:29 | 1464 |   3    281 2a02:a445:6a86:1:e815:5ed4:6a13:6304/128
> 2018-02-14 09:32:29 | 1464 |                                     On-link
> 2018-02-14 09:32:29 | 1464 |   3    281 2a02:a445:6a86:1:f1c3:f487:3421:106e/128
> 2018-02-14 09:32:29 | 1464 |                                     On-link
> 2018-02-14 09:32:29 | 1464 |   3    281 fe80::/64                On-link
> 2018-02-14 09:32:29 | 1464 |   2    331 fe80::/64                On-link
> 2018-02-14 09:32:29 | 1464 |   2    331 fe80::28bc:630:3f57:fdf6/128
> 2018-02-14 09:32:29 | 1464 |                                     On-link
> 2018-02-14 09:32:29 | 1464 |   3    281 fe80::e815:5ed4:6a13:6304/128
> 2018-02-14 09:32:29 | 1464 |                                     On-link
> 2018-02-14 09:32:29 | 1464 |   1    331 ff00::/8                 On-link
> 2018-02-14 09:32:29 | 1464 |   3    281 ff00::/8                 On-link
> 2018-02-14 09:32:29 | 1464 |   2    331 ff00::/8                 On-link
> 2018-02-14 09:32:29 | 1464 | ===========================================================================
> 2018-02-14 09:32:29 | 1464 | Persistent Routes:
> 2018-02-14 09:32:29 | 1464 |   None
> 2018-02-14 09:32:29 | 1464 | -->> (exitCode: 0)
> 2018-02-14 09:32:29 | 1464 | Default Gateway:192.168.2.254
> 2018-02-14 09:32:29 | 1464 | VPN Gateway: *************
> 2018-02-14 09:32:29 | 1464 | Internal Address: 10.40.10.125
> 2018-02-14 09:32:29 | 1464 | Internal Netmask: 255.255.224.0
> 2018-02-14 09:32:29 | 1464 | Internal Gateway: 10.40.0.1
> 2018-02-14 09:32:29 | 1464 | Interface idx: "22" ("Ethernet 2")
> 2018-02-14 09:32:29 | 1464 | <<-- [EXEC] route add ************* mask 255.255.255.255 192.168.2.254
> 2018-02-14 09:32:29 | 1464 |  OK!
> 2018-02-14 09:32:29 | 1464 | -->> (exitCode: 0)
> 2018-02-14 09:32:29 | 1464 | MTU: 1300
> 2018-02-14 09:32:29 | 1464 | <<-- [EXEC] netsh interface ipv4 set subinterface "22" mtu=1300 store=active
> 2018-02-14 09:32:29 | 1464 | Ok.
> 2018-02-14 09:32:29 | 1464 | 
> 2018-02-14 09:32:29 | 1464 | -->> (exitCode: 0)
> 2018-02-14 09:32:29 | 1464 | Configuring "22" interface for Legacy IP...
> 2018-02-14 09:32:29 | 1464 | <<-- [EXEC] netsh interface ip set interface "22" metric=1
> 2018-02-14 09:32:29 | 1464 | Ok.
> 2018-02-14 09:32:29 | 1464 | 
> 2018-02-14 09:32:29 | 1464 | -->> (exitCode: 0)
> 2018-02-14 09:32:29 | 1464 | <<-- [EXEC] netsh interface ip set address "22" static 10.40.10.125 255.255.224.0
> 2018-02-14 09:32:29 | 1464 | 
> 2018-02-14 09:32:29 | 1464 | -->> (exitCode: 0)
> 2018-02-14 09:32:29 | 1464 | <<-- [EXEC] netsh interface ip add dns "22" 10.19.32.24 index=1
> 2018-02-14 09:32:29 | 1464 | The object is already in the list.
> 2018-02-14 09:32:29 | 1464 | 
> 2018-02-14 09:32:29 | 1464 | 
> 2018-02-14 09:32:29 | 1464 | -->> (exitCode: 1)
> 2018-02-14 09:32:29 | 1464 | <<-- [EXEC] netsh interface ip add dns "22" 10.176.10.14 index=2
> 2018-02-14 09:32:29 | 1464 | The object is already in the list.
> 2018-02-14 09:32:29 | 1464 | 
> 2018-02-14 09:32:29 | 1464 | 
> 2018-02-14 09:32:29 | 1464 | -->> (exitCode: 1)
> 2018-02-14 09:32:29 | 1464 | done.
> 2018-02-14 09:32:29 | 1464 | Configuring Legacy IP networks:
> 2018-02-14 09:32:29 | 1464 | Route configuration done.

Now going to downgrade to see if that works, and will post that log file as well.

[LOG PLACEHOLDER]
