### ISSUE TITLE
No Traffic Flow V1.51-1.52

### ISSUE THREAD

**Issue by bryanzim** [openconnect/openconnect-gui#197]
### Description of the Issue
Windows 10/Windows7/Windows Server 2016 - Can connect to Cisco VPN with OpenConnect GUI V1.5.0 and traffic flows properly.  With OpenConnect GUI V1.5.1 or V1.5.2 the connection succeeds but there is not traffic that can be flowed.

### Specifications
V1.5.1 or V1.5.2
Windows 10/Windows 7/Windows Server 2016

### Steps to Reproduce the Issue
1.  Install OpenConnect GUI V1.5.0
2. Set up a connection to a Cisco VPN with a single group listed after connection
3. Verify operation
4. Install OpenConnect GUI V1.5.1 and V1.5.2
5. Connection does not show group list
6. Connection show sucessfull
7. No traffic flows

### Expected Behavior
Works properly

### Actual Behavior
Connection but no traffic

**Comment by bryanzim** [comment]
The logs contain sensitive information so I do not wish to share.
Yes, I did recreate profile in newest version.

The only immediate difference in the logs is the lack of the line
2017-09-27 10:01:49 | 1fc8 | Saving group: XXX

For the newer versions, i.e. 1.5.1-1.5.2.

My opinion is that the automatic selection for a single group may not be working properly.

**Comment by horar** [comment]
@bryanzim 
- group auto-selection come with v1.5.2, in previous version user has to select it manually
- probably the problem appears earlier and missing the group-selection is the result of previous error. Ehm I'm rewritting couple of parts to get cleaner UI with more config-options & better logging.

If possible, could you send me your server name? (here or to my gmail address when you want keep secret server name). I don't need vpn credentials... I will try just open session to get grooup list and debug it what's go wrong...
Thanks

**Comment by bryanzim** [comment]
What is your gmail address?

**Comment by horar** [comment]
> What is your gmail address?

lubomir \<dot\> carik \<at\> gmail \<dot\> com
