### ISSUE TITLE
Error during build on Mac OS Sierra (with latest XCode)

### ISSUE THREAD

**Issue by vin-d** [openconnect/openconnect-gui#198]
### Description of the Issue
Hi, because of bug #179 and #160 I'm trying to build openconnect-gui on my machine.
having followed every directive to compile I get the cmake command which fails : 

```
MacBook-Pro-2:build-release myself$ Qt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 cmake -DCMAKE_BUILD_TYPE=Release ..
CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/Platform/Darwin-Initialize.cmake:121 (message):
  Ignoring CMAKE_OSX_SYSROOT value:

  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk

 because the directory does not exist.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/CMakeSystemSpecificInitialize.cmake:8 (include)
  CMakeLists.txt:13 (project)


-- Building openconnect-gui v1.5.2 [cmake]
-- Library ‘GnuTLS’ found at /usr/local/lib/libgnutls.dylib
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindPkgConfig.cmake:36 (find_package_handle_standard_args)
  CMake/Modules/FindOpenConnect.cmake:26 (find_package)
  CMake/Includes/ProjectDependencies.cmake:24 (find_package)
  CMakeLists.txt:31 (include)
```

### Specifications
- **Version**: Sierra 10.12.6
- **Platform**: Mac OS. Developer tools and XCode installed today : 
I notice that I don't have a directory 
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
```
but I have a directory
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
``` 
I assume this happens because I have a recent version of XCode installed.
### Questions
- is it normal ? do other users have the same problem ?
- is it because CMake has to be updated to a newer version since High Sierra came out ?
- what do you propose as a solution ?
Thank you.

**Comment by horar** [comment]
Hi,
- I fixed SDK path, it was not updated yet for most recent Xcode (it was only warning)
- about missing pkg-config - I don't have this problem. I'm using HomeBrew. May be, you have to update your PATH variable so it points to all correct locations in /usr/local/opt .... bin/

**Comment by vin-d** [comment]
thank you, it works well now !

and for the pkg-config I just had to do a quick
```
brew install pkg-config
```
it oculd be useful to had that line here
https://github.com/openconnect/openconnect-gui/blob/develop/docs/dev_commandLine.md
in the ``# Install dependencies`` section

**Comment by horar** [comment]
Thanks, yes - more tools could be mentioned as dependency on macOS...
