### ISSUE TITLE
macOs 10.13.2 failing to launch app

### ISSUE THREAD

**Issue by Celerrime** [openconnect/openconnect-gui#201]
### Description of the Issue
I updated to macOS High Sierra 10.13.2 Developer Beta (Version 5) which seemed to have broken openconnect-gui. Prior to this, I was able to launch the app and connect to VPN. Now reaching an error.

### Specifications
- openconnect v7.08; using the pre-built binary 
[openconnect-gui-v1.5.1-error-dump.txt](https://github.com/openconnect/openconnect-gui/files/1520136/openconnect-gui-v1.5.1-error-dump.txt)

openconnect-gui-1.5.1-Darwin.dmg
- macOS High Sierra 10.13.2 Beta (version 5)

### Steps to Reproduce the Issue
1. Update to latest macos High Sierra beta (version 5) in the app store
2. Launch openconnect-gui

### Expected Behavior
Dialogue pops up asking for admin privileges. I provide the credentials and the app launches without error.

### Actual Behavior
Error dialogue pops up with message:
Failed opening file /Users/user/Library/Application Support/OpenConnect-GUI Team/OpenConnect-GUI/logs/OpenConnect-GUI.txt for writing: Operation timed out

**Comment by Celerrime** [comment]
The openconnect CLI works, just not the GUI version.

**Comment by horar** [comment]
Hi, thanks for info, may be, could you please share more details? Are you building the gui app from source code? If yes, which branch/tag? or 'r you runing some pre-build binary?
Thanks,
Lubomir.

**Comment by Celerrime** [comment]
Updated ticket with pre-built binary version info and the Problem Report macOs dumped me.

**Comment by horar** [comment]
Thanks. Version 1.5.1 is quite old GUI build for macOS and actually it is the only one published (because homebrew is not aimed to be used for release builds).

Problem with access to log file was fixed in source code. The workaround could be remove this file.... or you can try to make your own build from source code.

**Comment by Celerrime** [comment]
Thanks! I built app from source and that resolve the issue.
