### ISSUE TITLE
Proxy Script address is ignored in Windows

### ISSUE THREAD

**Issue by mfuentescas** [openconnect/openconnect-gui#203]
### Description of the Issue
The proxy script address sent by my connection is just ignored by OpenConnect-GUI.

### Specifications
- **Version**: 1.5.2 (32 bits)
- **Platform**: Windows 10 (64 bits)

### Steps to Reproduce the Issue
1. Connect to a network using a SmartCard and the protocol Cisco AnyConnect.

### Expected Behavior
It should set the proxy script address of my system and restore mine when disconnected.

### Actual Behavior
Proxy script address received in log viewer is ignored by OpenConnect-GUI, so my connection is not successfully.

For those people which needs a easy workaround, you will have here my own modification of "vpnc-script-win.js" in the attached file (renamed with a ".txt" added in the end of the filename). To be easy to follow the lines that I have added to the default script are marked here with the variable / mark "CUSTOMIZATION_by_MAFC".
[vpnc-script.js.txt](https://github.com/openconnect/openconnect-gui/files/1538576/vpnc-script.js.txt)

NOTES: 
- This modification is forcing the use of internal gateway because in my case this is ignored.
- In my case I needed to run the OpenConnect-GUI as admin.

**Comment by horar** [comment]
In present, the openconnect-gui use only system defined proxy. Will check what can be done with this scenario. Btw. just a quick question - does your proxy setup works with bundled command line client without script modification? Thanks.

**Comment by mfuentescas** [comment]
I have just tested with OpenConnect command line tool included* in your OpenConnect GUI and keeping the original script "vpnc-script.js" and I got the same result that in the GUI one explained in this ticket:

- I got a correct connection (with a right IP and mask).

- No gateway added (because the command used by the script was incomplete: 
`route add 185.185.185.185 mask 255.255.255.255 192.168.178.1)`

- No proxy script address.

- So I am connected by I have no access to any host.

For all of these issues I need my modification in your script.


Note*: My MSDOS commands:
`
cd  "C:\Program Files (x86)\OpenConnect-GUI\"
openconnect.exe -c "system:win:id=dummy;type=privkey;name=Dummy%20de%20Dummy" vpn.dummy.com
`

**Comment by mfuentescas** [comment]
I would like to enhance my customization of the "vpnc-script.js" enabling it only in the case of using a particular profile. 
Is there any way to detect the profile name or something else used by OpenConnect GUI?

**Comment by horar** [comment]
Hi, it is more complicated. At first, this project is just a GUI on top of great [openconnect project](http://www.infradead.org/openconnect/).

Yes, the script is not perfetct, looks like the proxy is not handled there. The design is something like: gui utilize the openconnect library, the library communicate with server, then it exports "few" environment variables and on the end the library invoke vpnc script. In your case should be exported 'CISCO_PROXY_PAC' environment variable )I guess, looking to openconnect source code) and IMHO we need to handle it in vpnc script. So the best way how to solve this could be discuss the problem on [openconnect mailing](http://www.infradead.org/openconnect/mail.html) list and sent there patches for vpnc. And this project will use them....

On other side - the gui use at this time only system proxy. It's on my todo list to extend configuration options...

**Comment by mfuentescas** [comment]
Thanks a lot for all your time and for this great software.

**Comment by horar** [comment]
Closing here, as there is nothing to do in GUI.
