### ISSUE TITLE
Can't ignore system-wide proxy setting on Windows 10

### ISSUE THREAD

**Issue by frankxu2004** [openconnect/openconnect-gui#208]
### Description of the Issue

When system-wide proxy is set, the openconnect-gui connects to VPN server through proxy, even though in the profile the Proxy is set unchecked. Is there a way to turn this feature off and let openconnect-gui connect to VPN directly?

### Specifications
- **1.5.1**: 
- **Windows 10 64bit**: 

### Steps to Reproduce the Issue

1. Set system-wide proxy in Settings
2. Connect to VPN in OpenConnect GUI
3. log says 
2017-12-15 01:00:17 |   e0 | OpenConnect-GUI VPN client (1.5.1) logging started...
2017-12-15 01:00:21 |   e0 | Setting proxy to: :@127.0.0.1:1080

### Expected Behavior
Connect to VPN server directly, since Proxy is unchecked in the profile settings.

### Actual Behavior
Connected to VPN server through the proxy.

**Comment by horar** [comment]
I'm sorry, there is no way to ignore system defined proxy... a bug :/

**Comment by frankxu2004** [comment]
Does the command line client's --no_proxy works around this?

**Comment by horar** [comment]
I didn't try. The command line client is other (upstream) project where the this GUI is build on. IMHO this is just a bug in GUI.
