### ISSUE TITLE
Cannot import p12 files with "error in parseing"

### ISSUE THREAD

**Issue by jyzhiyu** [openconnect/openconnect-gui#211]
Description of the Issue
Some p12 files can be imported into OpenConnect-GUI client in some computers, but they can not be imported into OpenConnect-GUI client in other computers with error in parsing.

Specifications
Version: 1.5.2 (32 bit)
Platform: Windows 10 64 bit

Steps to Reproduce the Issue
I am unable to give a confirmed step to reproduce this issue. The p12 file can be accepted in my PC but it not can be accepted in other PC with same OS env.

Actual Behavior
The logs shows that "error in parsing"

Other Information
All p12 and its password can be work fine.

**Comment by horar** [comment]
Hi, the issue with importing of p12 file on that computer is permanent, or when you try again, it works? It if the problem is permanent, could it be possible to generate fake-p12 file which is always rejected and share them here? (no need to log-in to your server). Thanks.

**Comment by horar** [comment]
Sorry, without more info, can't help.
