### ISSUE TITLE
Computer freeze

### ISSUE THREAD

**Issue by jeffshead** [openconnect/openconnect-gui#212]
### Description of the Issue
Computer freezes a couple of seconds after right-clicking the systray icon and selecting Quit. Get a very fast, repetitive hum from speakers like there is a race condition or a loop.

### Specifications
- **Version**: 1.5.2
- **Platform**: Windows 7 x64

### Steps to Reproduce the Issue

1. Use OpenConnectGUI to connect to your VPN
2. Right-click the systray icon and select Quit. 

### Expected Behavior
Disconnect from VPN and close OpenConnectGUI.

### Actual Behavior
Computer freeze. Have to hard reset.

### Other Information
Never did this with previous versions.

**Comment by horar** [comment]
Never observed this problem yet. Can you share more info?

1. is this reproducible i.e. freeze appear always or sometimes
2. is it about application freeze or whole system freeze
3. the freeze appears only when you you quit via systray menu in connected state or in disconnected as well?
4. do you find some information in system application - "Event Viewer" related to this application?
5. could you please upload the log file?

**Comment by jeffshead** [comment]
1. 50%
2. Whole system freeze
3. Only able to reproduce when quit via systray in connected state
4. No info in event viewer.
5. Where can I send log so it is not publicly available?

**Comment by horar** [comment]
You can send it directly to [me](mailto:Lubomir.Carik@gmail.com)

**Comment by jeffshead** [comment]
Sorry... I forgot to update this report. The issue was caused by the SRWare Iron browser on Windows. I had been using that browser, without issue, for a couple of years. The issue started with the previous couple of version releases around the time I reported this issue. I stopped using the browser so I don't know if they fixed the issue or not.
