### ISSUE TITLE
Menubar item on macOS doesn't behave like a native menubar app

### ISSUE THREAD

**Issue by sodle** [openconnect/openconnect-gui#214]
I'm seeing two integration issues with the app on macOS High Sierra (10.13.2):

- Clicking the menubar icon while in a fullscreen app does not show the menu, only highlights the icon. 

- The icon cannot be moved around the menu bar by holding Command and dragging it.

These issues are not present in macOS's built-in icons (Spotlight, battery, AirPort, etc.) or in other third-party ones (BetterTouchTool, Caffeine, SpiderOak, etc.)

**Comment by horar** [comment]
What version of app?

Can't reproduce these issues with develop-version & Qt 5.10 on macOS 10.13.2

**Comment by sodle** [comment]
1.5.1-dirty, the latest version from homebrew cask. Reinstalling the same version fixed on my end. Weird.

**Comment by sodle** [comment]
The first issue also persists when building from the develop branch.

**Comment by horar** [comment]
I try to install ask version but both mentioned issues works fine for me (there was other painting issue).

Do you use Qt 5.10 or older for develop-branch building?

Anyway, I will disable maximize button. There is no need for them...

**Comment by horar** [comment]
I try it no multiple pc's and can't reproduce it :/
Could be something in your environment or in Qt...
