### ISSUE TITLE
Reconnect not work in sometime

### ISSUE THREAD

**Issue by shanecode** [openconnect/openconnect-gui#215]
### Description of the Issue

When reconnect  and generated ip is change ,openconnect-gui give the message "gave different Legacy IP address (172.16.18.5 != 17.16.18.20)"
### Specifications
- **Version**: 1.5.2
- **Platform**: Windows 10 x64

### Steps to Reproduce the Issue

1. Change the ocserv config predictable-ips = false.
2. Connect the ocserv use openconnect-gui.
3. Disable the network and enable it.

### Expected Behavior

Reconnect work .
### Actual Behavior

Reconnect fail.
### Other Information
openconnect log : gave different Legacy IP address (172.16.18.5 != 17.16.18.20)

**Comment by horar** [comment]
Do you have this problem only with GUI or with console version as well?

Btw. I think, it will be related path mentioned in [OpenConnect - December 2017 Archives by thread](http://lists.infradead.org/pipermail/openconnect-devel/2017-December/thread.html)
