### ISSUE TITLE
garbled gui-settings with populated token-field

### ISSUE THREAD

**Issue by pichwo** [openconnect/openconnect-gui#220]
screenshot showing up garbled results - the otp-field was polulated correctly but no way to keep it ...

![2018-01-31 17_20_57-edit - openconnect-gui vpn client](https://user-images.githubusercontent.com/12297770/35634750-b8749488-06ac-11e8-9e28-9df711d751c1.png)

**Comment by horar** [comment]
The otp field was here entered or loaded or? Please share more details how to get this result.
Yes, this field should start with '0x' or 'base32:' prefix.

**Comment by pichwo** [comment]
just straightforward make a new account on a new installation. you have to enter mandatory fields.

please use e.g. :  "acme supersever blah blah" / "bigdata-bulshit.wizards.acme.com:11011".

afterwards try to fille the token field with some "0x727672fd0073954e40bdf774f4356fcd2f8fb8cc,0" or "base32:OJ3HF7IAOOKU4QF5652PINLPZUXY7OGM,0" and save it.

watch data from mandatory fields now in token field. (see screenshot above)

regards wp

**Comment by pichwo** [comment]
(offtopic, but mandatory information pls,:)

if i enter a "@otpconfig-file" to read otp-information from there -
what is the default (FULL-)path openconnect will expect to find files without preceding path specified ?

C:\Program Files (x86)\OpenConnect-GUI ??
C:\Users\admin\AppData\Local\OpenConnect-GUI Team ??
<somewhere else> ??

... and is ist possible to specify a full path ? e.g. "@c:\somewhere\otpconfig-file" ????
... does this path if possible have to be specified AS IS or somehow escaped ? e.g. "@c:\\somewhere\\otpconfig-file" ????
... or with foward-slashes instead of backslashes ? e.g. "@c:/somewhere/otpconfig-file" ????
... or in cygwin-notation ? "/cygdrive//c/somewhere/otpconfig-file" ????
... or in mingw-notation ? <whatever-posix-path besides standard windows paths> ???

i would be VERY happy NOT to have to do excessive trial-and-error about the topic .... ;-)

**Comment by pichwo** [comment]
hi - any time horizon for 1.5.3 ???
i am depending heavily on ocserv /w otp since all infrastructure is already migrated to 2fa and the cisco vpn which is primary access-point has to be cancelled asap.

**Comment by horar** [comment]
March 2018

**Comment by pichwo** [comment]
yeah - march ;-)

bump it up

in general i want to say, that i appreciate your work very much, because it is essential for contemporary use-cases in window$ to get users aquainted to non-m$ solutions as is foss-ocserv ...
to stress again - foss can only be achieved by usability

bg w.
