### ISSUE TITLE
Windows native VPN

### ISSUE THREAD

**Issue by Akababa** [openconnect/openconnect-gui#222]
### Specifications
- **Version**: 
- **Platform**: 

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Other Information

Is there a way to install openconnect in the Windows 10 native VPN client? I couldn't find any documentation on windows 10 VPN protocols so if anyone could point me in the right direction I would love to get it working!

**Comment by horar** [comment]
I'm not aware about this possibility.

**Comment by sergiomb2** [comment]
yeah , same problem here after investigate, windows 8.1 and windows 10 , don't have clients (free and opne) to connect to openconnect ,i.e. vpn cisco client "native"  support cease in windows 7 ... ,
What alternative do we have for windows 8.1 and 10 ?
