### ISSUE TITLE
openconnect-gui website download link broken

### ISSUE THREAD

**Issue by nsdecicco** [openconnect/openconnect-gui#223]
As the title states, the download links on https://openconnect.github.io/openconnect-gui/ download the latest commit of the 'gh-pages' (website) branch instead of the master branch, as I presume it should. I.e., these point to

```
https://github.com/openconnect/openconnect-gui/{zipball,tarball}/gh-pages
```

instead of

```
https://github.com/openconnect/openconnect-gui/{zipball,tarball}/master
```

**Comment by horar** [comment]
Thanks for notification, the page is generated by GitHub, by I will check why these buttons point to wrong branch...
