### ISSUE TITLE
There was an issue initializing the vpn (pipe setup fails)

### ISSUE THREAD

**Issue by weiweihaoyouwei** [openconnect/openconnect-gui#224]
### Description of the Issue
hi, my OS is windows10 version 1709 64-bit and my OpenConnect-GUI version is 1.5.2.
At first, the software was working fine, but after a few days, clicking the "connect" button each time, it prompts: There was an issue initializing the vpn (pipe setup fails).
I try to view the log, get the following information:
2018-03-06 11:57:41 | 2a88 | OpenConnect-GUI VPN client (1.5.2) logging started ...
2018-03-06 11:58:08 | 2a88 | invalid socket

First, I tried these methods:
1, Run this program with administrator privileges
2, Run this program in compatible mode (win8 and win7)
3, reconfigure the software
4, reinstall the software
The above methods are nothing more than to solve the problem.

Finally, I reinstall the system, the software can be used normally, but after a few days, the same problem occurs again.
I doubt because the windows update or other software I installed affected the use of OpenConnect-GUI, but because of too little log information, I was not sure where the problem was. Please help me, thanks!

### Specifications
- **Version**: 1.5.2
- **Platform**: windows10  64-bit version 1709

### Steps to Reproduce the Issue
1. start the application
2. click the "connect" button

### Expected Behavior
Connect to the server

### Actual Behavior
it prompts: There was an issue initializing the vpn (pipe setup fails).

**Comment by horar** [comment]
hi, hard to identify the issue from 2 log lines. Some hints ... e.g. this software doesn't play well with official Cisco Anyconnect clients; you can try re-install tap-drivers package...

**Comment by horar** [comment]
I guess the Cisco AnyConnect was installed; no more details, closing for now

**Comment by Ximalas** [comment]
I had the very same issue after ESET NOD32 decided to upgrade itself to 12.0.27.0. Even ssh-add had an issue when communicating with ssh-agent in Cygwin. Both issues disappeared once I uninstalled NOD32 and reinstalled it from a manually downloaded executable. If the OP still experience this issue, then check your antivirus software. (A similar episode last summer led to Windows becoming virtually unuseable until I forcefully removed NOD32 using its removal tool.)
