### ISSUE TITLE
some clients may need more time to start TAP-windows

### ISSUE THREAD

**Issue by shaellancelot** [openconnect/openconnect-gui#225]
if (CreateProcessW(NULL, script_w, NULL, NULL, FALSE, cpflags, script_env, NULL, &si, &pi)) {
    ret = WaitForSingleObject(pi.hProcess,10000);
    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);
    if (ret == WAIT_TIMEOUT) ret = -ETIMEDOUT;
    else ret = 0;
} else {
    ret = -EIO;
}

In some case, 10 seconds may not longer enough to start TAP-windows，and I got the error log as below.
Failed to spawn script 'C:\Program Files (x86)\openconnect\vpnc-script.js' for connect: 找不到映像文件中指定的资源类型。

**Comment by shaellancelot** [comment]
around 5 seconds after the error log is output, the TAP-windows then was started successfully.

**Comment by horar** [comment]
Wrong place; can't help you. This should be discussed [here](http://www.infradead.org/openconnect/mail.html)
