### ISSUE TITLE
If WScript.Sleep(2000) in vpnc-script.js can be optimized with shorter loop interval.

### ISSUE THREAD

**Issue by shaellancelot** [openconnect/openconnect-gui#226]
for (var i = 0; i < 50; i++) {
    echo("Waiting for interface to come up...");
    WScript.Sleep(200);
    if (execWithoutLog("route print").match(if_route)) {
    return true;
}

Like the code above, and the entire setup-tunnel-time can be shorter.

**Comment by horar** [comment]
Wrong place; can't help you. This should be discussed [here](http://www.infradead.org/openconnect/mail.html)
