### ISSUE TITLE
traffic not going through vpn

### ISSUE THREAD

**Issue by tierra-bronza** [openconnect/openconnect-gui#228]
i use username & password certification and it works on cisco anyconnect client. but when it comes to openconnect, though the client suggestes i'm connected to vpn server, i trace a random ip address and find the traffic not passing through a vpn tunnel. server: ocserv 0.11.11
around one minute after establishing DTLS connection, the client reconnects and loops:
SSL read error: The TLS connection was non-properly terminated.; reconnecting.

**Comment by jan-glx** [comment]
see #190
