### ISSUE TITLE
no-route a.k.a X-CSTP-Split-Exclude configure on ocserv not working with OpenConnect GUI

### ISSUE THREAD

**Issue by keekychen** [openconnect/openconnect-gui#230]
Enviroment: 
**Client:**
Windows 7 64-bit, OpenConnect-GUI version is 1.5.{1,2,3}
**Server:**
ocserv 0.10.11, ocserv 0.11.8 - Cisco compatible mode enabled

In ocserv's configuration, the “no-route” command defined which IP segment will go from local gateway instead of VPN gateway. May looks like: 

> ...
> "no-route = 1.1.0.0/255.255.0.0"
> "no-route = 2.2.0.0/255.255.0.0"
> ...

Normally, after user dialed vpn, the `vpn client` will triggering  to rewrite local host route(s) point to local gateway based on `“no-route”` configuration as split tunnels.
 
However this is not working on OpenConnect-GUI version 1.5.{1,2,3}, but works on Cisco anyconnect clients.

In OpenConnect-GUI Log, I can see info from server do pushed to local 

> 2018-03-27 12:59:05 |  c74 | X-CSTP-Split-Exclude: 1.1.0.0/255.255.0.0
> 2018-03-27 12:59:05 |  c74 | X-CSTP-Split-Exclude: 2.2.0.0/255.255.0.0

But no local host routing set command been found in OpenConnect-GUI log
`“cmd -> route print”` also confirm only 0.0.0.0 with small metric in local routing table but no detailed split routing entries.  

> Network Destination        Netmask          Gateway       Interface  Metric
>           0.0.0.0          0.0.0.0    192.168.1.1     192.168.1.28     21
>           0.0.0.0          0.0.0.0    172.16.2.1      172.16.2.66      2                   <- VPN subnet

...

Do you mind to check why `X-CSTP-Split-Exclude` not trigger local routing commands by `OpenConnect-GUI`  to rewrite local routing table?

Thank you.

**Comment by horar** [comment]
@keekychen. is this problem related to GUI only or to openconnect cli as well? Thanks.

**Comment by keekychen** [comment]
@horar thank you, it looks like in pure cli, openconnect.exe acts same as GUI. I will raise this to openconnect author.

**Comment by horar** [comment]
@keekychen , thanks for update. Please provide the patch to mentioned mailing list. When accepted, we can/will use it in GUI as well. The openconnect and vpnc-script are 3rd party components for this UI project. I'm trying keep here just gui-related script modification (not yet accepted into upstream vpnc script project etc.).
Thanks!
