### ISSUE TITLE
Connecting to vpn says  Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).

### ISSUE THREAD

**Issue by eduardite** [openconnect/openconnect-gui#234]
Hi, I am connecting to my company vpn using cisco anyconnect
then I want to use openconnect command line something similar to: 
openconnect --authgroup=Groupx -u userid@company.com --interface vpn1 server.company.com:443 
It starts to connect but in the end it fails. 
I tried adding -m 1322 and others but it keeps failing. 

This windows10, this is the first time I try this on windows. 
I am able to do it on Linux (networkmanager + openconnect). 

What could be failing?

 Connected as 158.98.207.177, using SSL
 Established DTLS connection (using GnuTLS). Ciphersuite (DTLS0.9)-(RSA)-(AES-128-CBC)-(SHA1).
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1331 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1330 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1329 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1328 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1327 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1326 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1325 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1324 -5)
 Failed to write to SSL socket: The transmitted packet is too large (EMSGSIZE).
 Failed to send DPD request (1323 -5)
 Detected MTU of 1322 bytes (was 1331)
 Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

Set up tun device failed
Cookie was rejected on reconnection; exiting.

**Comment by horar** [comment]
Hi, I can only guess what are u doing :/ ... e.g. what version of openconnect? Released or some snapshot?
With last version the EMGSIZE warnings are OK, the utility try to detect the value automatocally.

I can indeed just guess - did you start openconnect.exe in console with admin rights?

**Comment by eduardite** [comment]
Thanks, 
Yes I started openconnect.exe in console (run as administrator) 
The file I downloaded is openconnect-gui-1.5.3-win32.exe and also tested openconnect-gui-1.5.2-win32.exe.


Another test I made: I managed to connect with another vpn software to my company.
I tried again with openconnect and failed again. But I could connect using cisco anyconnect. While I was connected with Cisco Anyconnect and tried the GUI version: I can see it attempts to connect while the cisco anyconnect gets disconnected and reconnects: eventually it connects, but the vpn doesn't work (openconnect) while cisco anyconnect (stays connected and works).

I tried again without cisco anyconnect: this time openconnect doesn't connect. 
Tomorrow I will test without the first vpn (to my company).

**Comment by horar** [comment]
Thank you for update.
Actually yes, some people faced similar problems in past. When using Cisco VPN software and free OpenConnect client software together. They fall into many problems. Other problem may be TAP driver/device sharing between commercial and free tools.... don't do it.
So, yes, use onle one of them i.e. uninstall Cisco & Tap drivers and install OpenConnect incl. TAP drivers and it may works as you expect... :-)

**Comment by eduardite** [comment]
Perfect, thanks.
