### ISSUE TITLE
Input Error: There is no script engine for file extension ".js".

### ISSUE THREAD

**Issue by opilo** [openconnect/openconnect-gui#239]
### Description of the Issue
Openconnect connects to the server but vpn is not set correctly. Here are some console logs:
```
 Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

Input Error: There is no script engine for file extension ".js".
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

Input Error: There is no script engine for file extension ".js".
```
### Specifications
- **Version**: 1.5.1 (I checked 1.5.3 it did not worked either)
- **Platform**: Windows 10 64-bit

**Comment by opilo** [comment]
This link helped fix the issue:
http://digcode.com/posts/m3570/Input-Error-There-is-no-script-engine-for-file-extension-js?g=posts&m=3570

Not sure if this is a openconnect-gui bug, JS files were associated to PHPStorm

**Comment by horar** [comment]
Hi, thanks for report and hint. It's not for first time when JS file suffix assignment issue was reported.

Indeed, this should be discussed in upstream [openconnect](http://www.infradead.org/openconnect/) project. But, I will update FAQ for this project.

**Comment by horar** [comment]
I have update this GUI project wiki, so it may help others if this problem appears again for someone.
