### ISSUE TITLE
how is $VPNFD applied to utunX

### ISSUE THREAD

**Issue by shaellancelot** [openconnect/openconnect-gui#240]
In tun.c, $VPNFD is set as environment variable for vpnc-script. But in vpnc-script, I do not find where $VPNFD is used.

So, how does openconect read from utun device?

Thanks!

**Comment by horar** [comment]
Yes. Exported variable is used only by vpnc script (IMHO). You are right, actual vpnc scripts doesn't use this variable.

I'm sorry, 'tun.c'? But, this is other story - other project. This is a GUI on top of openconnect.

The best place to ask is the openconnect mailing list.
(or, just simple google for 'VPNFD openconnect' and you will get few hints where and how is used this openconnect variable with proxies)

**Comment by shaellancelot** [comment]
Thank you very much.
