### ISSUE TITLE
Feature request: support OpenVPN protocol?

### ISSUE THREAD

**Issue by jcrben** [openconnect/openconnect-gui#241]
Apologies if this has been requested before or it's rather outlandish. Totally understand if this is entirely out of scope - feel free to close. But at the very least it seems like this might server as a foundation for someone else who might be interested.

Use case: I use both mac and linux and I'd like to have a cross-platform, flexible VPN client. I'd prefer linux, but mac is common with colleagues and more stable.

Currently I'm only connecting to OpenVPN servers using Tunnelblick on mac and `openvpn` on linux.

**Comment by horar** [comment]
OpenConnect & OpenVPN are different technologies. I don't see addon value at this time to implement both one, may be once, later...
