### ISSUE TITLE
Make DTLS handshake timeout longer and/or configurable

### ISSUE THREAD

**Issue by nielspeen** [openconnect/openconnect-gui#26]
While traveling (and using congested hotel Wi-Fi networks) I often fail to setup a DTLS connection to servers overseas. The DTLS handshake will timeout. Meanwhile OpenVPN or other UDP protocols manage to establish successfully. (And once OpenConnect itself does get through properly, it works without issue.)

Is the low handshake timeout a performance consideration? (E.g. if the handshake is slow, UDP is probably not worth using?) I would prefer if the default were a bit higher and the value made configurable.

**Comment by horar** [comment]
Hi @nmav ... is this about **dtls_attempt_period** parameter declared by:
`int openconnect_setup_dtls(struct openconnect_info *vpninfo, int dtls_attempt_period);`

**Comment by nmav** [comment]
Yes. Setting that to 20-30 seconds would be more reasonable than the default.
