### ISSUE TITLE
An error occurred installing the TAP device driver

### ISSUE THREAD

**Issue by buchuitoudegou** [openconnect/openconnect-gui#260]
**Describe the bug**
When installing it, the installer tell me `An error occurred installing the TAP device driver`

**To Reproduce**
I tried to run the `tap-windows.exe` separately but  it is stuck in `TAP update (tap0901)(Maybe require confirmation)` for a long time. Then I got an error `Updating drivers for tap0901 from C:\Program Files\TAP-Windows\driver\OemVista.inf. UpdateDriverForPlugAndPlayDevices failed, GetLastError = 1460.`

**Desktop**
 - OS: Windows10
 - Version: OpenConnect-GUI-1.5.3

**Comment by horar** [comment]
hi, thanks for report. This version is long time out.. may be try:
- uninstall existing tap driver
- install TAP as administrator

Do you use other VPN client?

**Comment by buchuitoudegou** [comment]
Thanks for your advice. But they don't work for me. 

I uninstalled other VPN clients and existing tap driver. But I met the same error when installing it as administrator. Are there any newer versions of OpenConnect?

**Comment by horar** [comment]
Hmm, hard to give more advices. TAP driver is comming from OpenVPN project. It is the last released version and nobody complains.
I know there are issues using multiple VPN clients together e.g. with OpenConnect, but after removal of everything it should work...

**Comment by buchuitoudegou** [comment]
Thanks for your advice. Maybe I should try using other VPN...Thank u anyway.
