### ISSUE TITLE
Does Your Product/Program Use a Certification named "srv-build-cd"?

### ISSUE THREAD

**Issue by Bj007pro** [openconnect/openconnect-gui#261]
So, this is going to be sounding very weird or strange, but today I did a Rating Scan with my main antivirus Comodo Internet Security Premium 11. It came back with a result with four Untrusted Certifications which three of them I already know what to do with, but my main interest is the _CORP/srv-build-cd_ certification.

I did a quick Google search and the only relating result was to your Openconnect-gui, it was the first result and every other result didn't relate.

I know this has a high chance that it has nothing relating to your product/program and I'm just making a fool out of myself making this issuse, but if there is another off chance you might know something, can you please mention it?

I've never ever tried to install your Openconnect-gui program.

![image](https://user-images.githubusercontent.com/24400879/52542677-36c46480-2e07-11e9-8848-b572a0008eac.png)

Thanks,

Bj007pro.

**Comment by horar** [comment]
This utility doesn't introduce certificates itself. Only when you connect to server and accept unsigned server certificates.
Looks like you are using sw that is conneccting to site with mentioned certificate in chain.

**Comment by Bj007pro** [comment]
> This utility doesn't introduce certificates itself. Only when you connect to server and accept unsigned server certificates.
> Looks like you are using sw that is conneccting to site with mentioned certificate in chain.

So. what should I do? Should I get my AV to clean it or trust it? I don't know who owns this certification.

**Comment by horar** [comment]
There is no relation of your certificate to this application. You mentioned it - you didn''t use this client application.
It's your decision. 
Personally, I will not trust this certificate until you figure who is the owner/producer.
