### ISSUE TITLE
OpenConnect-Gui Crashes when CISCO_SPLIT_INC* is already populated

### ISSUE THREAD

**Issue by spetragl** [openconnect/openconnect-gui#29]
I ran into this one by first setting the CISCO_SPLIT_INC* environment variables .
When you invoke OpenConnect-gui.exe and connect, it crashes.
David has the fix for this one; it was incorporated into OpenConnect.exe .

**Comment by nmav** [comment]
That would be included in the next update. Probably in the next few months.
