### ISSUE TITLE
Autoselect predefined group in profile

### ISSUE THREAD

**Issue by brunis** [openconnect/openconnect-gui#30]
<subject> says all

**Comment by nmav** [comment]
No idea what is meant.

**Comment by brunis** [comment]
When you are connecting to a hosting provider that uses the same cisco vpn to segment several customer vpn's .. you are prompted with a group choice..  i want to be able to preselect my group number in my vpn profile, so i don't have to pick it every time.

**Comment by nmav** [comment]
The group is saved after selection so you shouldn't need to select it every time. There could be an option to write your group on the edit dialog though.

**Comment by brunis** [comment]
no it's not saved. there's a groupname label in the profile edit, but no input to select or write anything.

**Comment by nmav** [comment]
I am unable to reproduce using ocserv. Do you see any line like "Select group" in the log? Could you run the openconnect cli in the server and paste or send me the output?

**Comment by brunis** [comment]
Hi,

Yes, i see "Select form: group_list"

small excerpt from my connection log:
Set-Cookie: webvpnlogin=1; secure
X-Transcend-Version: 1
HTTP body chunked (-2)
Please enter your username and password.
Please enter your username and password.
Select form: group_list
Text form: username
Password form: password
POST https://vpn.scannet.dk/+webvpn+/index.html

**Comment by nmav** [comment]
Could you search your registry for openconnect-gui "folder" using regedit. Then find your server and check whether there is a key with your group name.

**Comment by brunis** [comment]
Yeah, found my entry "server:vpn.scannet.dk" but there are no group
entries..  which reflects what i'm seeing in the ui.

I will try to re-add it and see what happens.

**Comment by jedvardsson** [comment]
I think what brunis means is that the argument --authgroup should be available to preconfigure in the UI. There is a labelled called "group" in the UI but it doesn't have a text field (on Mac at least).

**Comment by nmav** [comment]
The --usergroup openconnect option is not yet supported; only the authgroup option.

**Comment by nmav** [comment]
I believe the usergroup can be implemented or worked around the following way:
use as URL https://my.server.com/usergroup

**Comment by nmav** [comment]
Not sure if we should add yet another group option, or simply document that on server input hover. @brunis @jedvardsson could you verify that the above resolves your issue?

**Comment by brunis** [comment]
That workaround is working for me, but why not fix the input field in the config that is missing?

**Comment by nmav** [comment]
This is not a workaround but how the usergroup is supposed to work :). The "authgroup" which you are asked for during login, is different from the "usergroup" which is set as part from URL. Not all servers support both.

**Comment by brunis** [comment]
Then openconnect should make that more clear, there is a "groupname" config entry with no input field.. and i'm prompted for a "GROUP" when connecting..  this is the part i'm fixing by appending /1051142 to my url ..  whichever way you go doesn't matter to me, it works for me now :)

**Comment by douglasg14b** [comment]
There should really be a way to type in the group name.... without it I can't perform any actions over the VPN, and I'm not prompted to enter a group name.
