### ISSUE TITLE
Enhancement: Display cscript output in log

### ISSUE THREAD

**Issue by spetragl** [openconnect/openconnect-gui#31]
It would be nice if the log function could append the cscript output of vpnc-script-win.js to the log Window so we can catch any errors. If would also be nice if the button was labeled.
Thanks

**Comment by nmav** [comment]
That should be the case in the latest version (0.9). Are you sure you don't see the vpnc-script output in your log?

**Comment by spetragl** [comment]
I installed v0.9.
I know the vpnc-script runs because after the window minimizes, I do a 'ROUTE PRINT' and I can see the changes .
But no CSCRIPT output appears in the log.

**Comment by nmav** [comment]
The log is saved in a temporary file within the home directory. If it cannot be opened you'll see a log entry with the reason, please copy paste that here.

**Comment by spetragl** [comment]
I checked and no such file appears in C:\Program Files (x86)\OpenConnect.
However a file openconnect-gui.XXXXXX in %TEMP% does appear with 0 bytes.

**Comment by nmav** [comment]
Could it be then that the script you have exits without printing anything? Could you debug the script while running by adding print items?

**Comment by spetragl** [comment]
Here’s the script; it’s loaded with ‘echo’s which I never see.
But all that aside, the software is working really well.
