### ISSUE TITLE
Minimize to task tray

### ISSUE THREAD

**Issue by badbob001** [openconnect/openconnect-gui#33]
Please add an option for the app to minimize to task tray IF the vpn is currently connected. So if the vpn is not established and you minimize the app, it will still show up in the taskbar. But if the vpn is connected and it is minimized either manually or automatically (via the 'Minimize on Connect' option), then it does not show up in the task bar but only show as a task tray icon.

**Comment by nmav** [comment]
I like the idea. A patch would always speed things up. Otherwise it will be queued for when I manage to allocate some time for it.
