### ISSUE TITLE
openconnect-gui says vpnc-script-win.js not found after the script runs

### ISSUE THREAD

**Issue by spetragl** [openconnect/openconnect-gui#34]
I get this on occasion in the log Window.
Failed to spawn script "vpnc-script-win.js, no more files" after that same script has completed.
I suspect an ERRORLEVEL=1 is being received in the Script and passed back to openconnect-gui .
Can you test if the file exists first?

**Comment by nmav** [comment]
That should be solved by the latest release (1.0). Please re-open if that is not the case.
