### ISSUE TITLE
In some systems the output from the vpnc-script is not displayed in log

### ISSUE THREAD

**Issue by spetragl** [openconnect/openconnect-gui#36]
It would be nice if the log function could append the cscript output of vpnc-script-win.js to the log Window so we can catch any errors. If would also be nice if the button was labeled.
Thanks

The log is saved in a temporary file within the home directory. If it cannot be opened you'll see a log entry with the reason, please copy paste that here (feel free to re-open the bug if it is still there).
 
I checked and no such file appears in C:\Program Files (x86)\OpenConnect.
However a file openconnect-gui.XXXXXX in %TEMP% does appear with 0 bytes.

A message is displayed saying vpnc.log not found.
If I pre-allocate the file in %TEMP%, the message goes away, but still no Cscript output.

**Comment by nmav** [comment]
As mentioned in the previous issue, this seems to be something related with your system. Please provide more information in order to address it.

**Comment by spetragl** [comment]
The only message I see is this:
Opened tun device My-TAP
TAP-Windows driver v9.21 (0)
Could not open C:/Users/spetragl/AppData/Local/Temp\vpnc.log

**Comment by spetragl** [comment]
I checked the Registry and .js can be invoked 2 ways; either Windowed, or Command-Console.
I don't know if this has any bearing on the execution of your code.

[HKEY_CLASSES_ROOT\JSFile\Shell]
@="Open2"

[HKEY_CLASSES_ROOT\JSFile\Shell\Open\Command]
@="C:\\Windows\\System32\\WScript.exe \"%1\" %*"

[HKEY_CLASSES_ROOT\JSFile\Shell\Open2\Command]
@="C:\\Windows\\System32\\CScript.exe \"%1\" %*"

**Comment by spetragl** [comment]
Can you post a sniplet of the code that calls the Java Script?

**Comment by nmav** [comment]
http://git.infradead.org/users/dwmw2/openconnect.git/blob/HEAD:/script.c#l463

**Comment by spetragl** [comment]
Nikos,
A few suggestions that might help clarify a few things.
These are just suggestions; use them as you like.

---------------------------------------------------------------------------------------------------
First thing I would do is around line 465, add a stat on the vpninfo->vpnc_script;
Something like this, just to make sure the script actually exists; if not, let em know.
  if(stat(vpninfo->vpnc_script, &statbuf) < 0)
  {
    fprintf(stderr, "Can't find file=%s, errno=%d\n",vpninfo->vpnc_script,errno);
    return(xx);
  }

---------------------------------------------------------------------------------------------------
At line 463 I see you are building your DOS command and line 485 you execute it.
I’m not sure what will be returned when I execute from a shortcut:
  "C:\Program Files (x86)\OpenConnect\openconnect-gui.exe" and I’ve checked “Run As Administrator”.

Line 482 you test if a Console Window exists and if so, share it.
But what if no Console Exists?
I don’t see any redirect of the STDOUT nor STDERR in
  "cscript.exe \"%s\"", vpninfo->vpnc_script)


---------------------------------------------------------------------------------------------------
At  line 500 you test the Return code of the spawn and/or execution.
Problem is, the message is unclear when an ERRORLEVEL=1 is returned by the script.
It might help if you interrogate the possible RCs.
  if  (ret == –EIO)
    "Failed to spawn script”
  else
    if (ret == –ETIMEOUT)
      “Timed Out Waiting For Process”  
    else
      “Script ended RC=” ret
NOTE: The code in line 465 (above) will not get here if the script is not found.

---------------------------------------------------------------------------------------------------

Let me know if this helps.

- Steve

**Comment by NikolaR** [comment]
Had this issue when running v1.1, but was resolved with v1.2.
Seems to be related to problem with executing connection script file.

**Comment by spetragl** [comment]
Do you have the latest compiled version somewhere I can download (other than GitHub) ?

**Comment by nmav** [comment]
Is there any issue getting it from github? You can also get it from http://download.cnet.com/ but you should be aware that they add crap in their installer.

**Comment by spetragl** [comment]
Github is fine, but I’m already running with that copy.

**Comment by greatz** [comment]
I received the same error message 
  "Could not open C:/Users/zoltann/AppData/Local/Temp\vpnc.log: 5" 
after I've modifed the vpnc-script.js including a typo/bug in it. :-) 

In that case, of course the vpnc.log was not created at all. 

You can try to detect this case in the code and/or add a hint to the error message like "make sure the vpnc-script.js was not modified and bug-free".

**Comment by nmav** [comment]
No input, so it seems it is resolved. Feel free to reopen with new information if it is not the case.

**Comment by frunzales** [comment]
I've been experiencing the same issue with v1.4.0/v1.4.1 and possibly earlier versions of the client.
