### ISSUE TITLE
vpnc-script.js not executed on Windows

### ISSUE THREAD

**Issue by irichter** [openconnect/openconnect-gui#38]
Per the DEFAULT_VPNC_SCRIPT set by [common.h:49](https://github.com/openconnect/openconnect-gui/blob/v1.1/common.h#L49) and used in VpnInfo::Connect() [vpninfo.cpp:464](https://github.com/openconnect/openconnect-gui/blob/v1.1/vpninfo.cpp#L464), the script to be executed is named "vpnc-script-win.js".

However, the script actually installed is named "vpnc-script.js". As a result, the script cannot be found and is not run, making the tunnel useless.

Possible solutions:
1. Modify DEFAULT_VPNC_SCRIPT to point to "vpnc-script.js".
2. Modify the installer to create a file named "vpnc-script-win.js" instead of "vpnc-script.js".
3. Add a required GUI option for the user to pick a script. (This should probably be used with caution, as if the user [launches the GUI with UAC bypassed](https://www.raymond.cc/blog/task-scheduler-bypass-uac-prompt/), they could then execute any code of their choosing with administrative privileges.)

As a work-around, renaming the installed script to "vpnc-script-win.js" works.

**Comment by nmav** [comment]
Thanks.

**Comment by thoughtchad** [comment]
Nice point release! I had dropped back to 0.9 due to strange issues where the tunnel stopped working, etc. 1.2 looks solid. No errors in the log, and solid DTLS on first connect. Really appreciate the effort here.
