### ISSUE TITLE
VNPC script help wanted

### ISSUE THREAD

**Issue by dvkwong** [openconnect/openconnect-gui#44]
When connecting vpn it seems the TAPS network adapter is not being setup correctly. The IPV4 settings fail to be applied. Is this an error/bug in the vpnc-script.js?

The vpnc.log snippet below
Interface: "Local Area Connection 3"
executing: route add 125.236.73.16 mask 255.255.255.255 192.168.1.1
 OK!
MTU: 1406
executing: netsh interface ipv4 set subinterface "Local Area Connection 3" mtu=1406 store=active
Element not found.
Configuring "Local Area Connection 3" interface for Legacy IP...
executing: netsh interface ip set interface "Local Area Connection 3" metric=1
Element not found.
executing: netsh interface ip set address "Local Area Connection 3" static 172.27.2.123 255.255.255.255 172.27.2.124 1
Element not found.
executing: netsh interface ip add dns "Local Area Connection 3" 172.27.4.240 index=1
The object is already in the list.
executing: netsh interface ip add dns "Local Area Connection 3" 172.27.7.240 index=2
The object is already in the list.

**Comment by dvkwong** [comment]
Ah renaming the adapter to TAPS seems to have resolved this issue.

**Comment by nmav** [comment]
Why would you have needed renaming the adapter? Have you renamed it prior to the issue?

**Comment by dvkwong** [comment]
Before the renaming the adapter was only being set with the IPV6 addresses, the IPV4 were failing to be set by the vpnc script, not exactly sure why.
