### ISSUE TITLE
Not routing thru to vpn connection, help wanted

### ISSUE THREAD

**Issue by dvkwong** [openconnect/openconnect-gui#45]
On Win7 when connecting to VPN all network requests are still being routed thru the local connection instead of the VPN connection.

Checking the routes everything looks ok with the vpn network metric at 2 etc

Anything I can try? Below is a comparison of the Openconnect and Cisco client route setup, the cisco one does work.

Open connect route

IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0      192.168.1.1     192.168.1.29     25
          0.0.0.0          0.0.0.0     172.27.2.103     172.27.2.102      2
    125.236.73.16  255.255.255.255      192.168.1.1     192.168.1.29     26
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    306
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    306
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    306
     172.27.2.102  255.255.255.255         On-link      172.27.2.102    257
      192.168.1.0    255.255.255.0         On-link      192.168.1.29    281
     192.168.1.29  255.255.255.255         On-link      192.168.1.29    281
    192.168.1.255  255.255.255.255         On-link      192.168.1.29    281
    192.168.134.0    255.255.255.0         On-link     192.168.134.1    276
    192.168.134.1  255.255.255.255         On-link     192.168.134.1    276
  192.168.134.255  255.255.255.255         On-link     192.168.134.1    276
    192.168.150.0    255.255.255.0         On-link     192.168.150.1    276
    192.168.150.1  255.255.255.255         On-link     192.168.150.1    276
  192.168.150.255  255.255.255.255         On-link     192.168.150.1    276
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    306
        224.0.0.0        240.0.0.0         On-link      172.27.2.102    257
        224.0.0.0        240.0.0.0         On-link      192.168.1.29    281
        224.0.0.0        240.0.0.0         On-link     192.168.150.1    276
        224.0.0.0        240.0.0.0         On-link     192.168.134.1    276
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    306
  255.255.255.255  255.255.255.255         On-link      172.27.2.102    257
  255.255.255.255  255.255.255.255         On-link      192.168.1.29    281
  255.255.255.255  255.255.255.255         On-link     192.168.150.1    276
  255.255.255.255  255.255.255.255         On-link     192.168.134.1    276
===========================================================================
Persistent Routes:
Network Address          Netmask  Gateway Address  Metric
0.0.0.0          0.0.0.0     172.27.2.103       1
===========================================================================

When using Cisco client (works)

IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0      192.168.1.1     192.168.1.29     25
          0.0.0.0          0.0.0.0     172.27.2.101     172.27.2.100      2
    125.236.73.16  255.255.255.255      192.168.1.1     192.168.1.29     26
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    306
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    306
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    306
     172.27.2.100  255.255.255.255         On-link      172.27.2.100    257
      192.168.1.1  255.255.255.255         On-link      192.168.1.29     26
     192.168.1.29  255.255.255.255         On-link      192.168.1.29    281
    192.168.134.1  255.255.255.255         On-link     192.168.134.1    276
    192.168.150.1  255.255.255.255         On-link     192.168.150.1    276
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    306
        224.0.0.0        240.0.0.0         On-link      192.168.1.29    281
        224.0.0.0        240.0.0.0         On-link     192.168.150.1    276
        224.0.0.0        240.0.0.0         On-link     192.168.134.1    276
        224.0.0.0        240.0.0.0         On-link      172.27.2.100    257
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    306
  255.255.255.255  255.255.255.255         On-link      192.168.1.29    281
  255.255.255.255  255.255.255.255         On-link     192.168.150.1    276
  255.255.255.255  255.255.255.255         On-link     192.168.134.1    276
  255.255.255.255  255.255.255.255         On-link      172.27.2.100    257
===========================================================================
Persistent Routes:
Network Address          Netmask  Gateway Address  Metric
0.0.0.0          0.0.0.0     172.27.2.110       1
0.0.0.0          0.0.0.0     172.27.2.101       1
===========================================================================

**Comment by nmav** [comment]
The best is to very that the script executed properly. What is the output of tracert to some IP it should route to?

**Comment by dvkwong** [comment]
This is trying to route via my modem.router. I think this is more to do with no connection on the adapter. Normally the Cisco adapter shows as connected however the TAP adapter has a status of Unidentified network in network connections.  

Tracing route to 172.27.6.48 over a maximum of 30 hops

  1     2 ms     1 ms     1 ms  Broadcom.Home [192.168.1.1]
  2     *        *        *     Request timed out.
  3    12 ms     7 ms     9 ms  ae-5-10.cpcak3-r2.tranzpeer.net [101.98.3.41]
  4    11 ms     8 ms     6 ms  ae-4-10.cpcak3-r2.tranzpeer.net [101.98.3.40]
  5    11 ms     7 ms     6 ms  ad-cpcak3-r2.tranzpeer.net [101.98.3.164]
  6     9 ms     7 ms    10 ms  pts-n.cpcak4-r1.tranzpeer.net [101.98.5.20]
  7    10 ms    10 ms    10 ms  pts-s.cpcak4-r1.tranzpeer.net [101.98.5.21]
  8     *        *        *     Request timed out.
  9     *        *        *     Request timed out.
 10     *        *     ^C

**Comment by nmav** [comment]
This has to do with the TAP adapter. There was some discussion in the mailing list that mentioned a similar issue in German windows. The reporter solved it by renaming the adapter. Could that be related to your issue?
http://article.gmane.org/gmane.network.vpn.openconnect.devel/2633

**Comment by nmav** [comment]
No input, so it seems it is resolved. Feel free to reopen with new information if it is not the case.
