### ISSUE TITLE
Please add static libraries for OSX to the repository

### ISSUE THREAD

**Issue by mike-lischke** [openconnect/openconnect-gui#46]
In order to build the gui on OSX I'd need the static libs for it. In the package included seem only Windows static libs. Can you please add those for OSX too? Thank you.

**Comment by nmav** [comment]
Currently the only way to build on OSX is via MacPorts. That is, until there is a maintainer for an OSX package.

**Comment by mike-lischke** [comment]
What do you mean by "until there is a maintainer"? Since openconnect-gui is in Ports there must be a maintainer already. Someone has compiled it for Ports and I'd expect it's the one that maintains this repo (would only be natural, no?).

**Comment by nmav** [comment]
There is a MacPorts maintainer but that is irrelevant to your question. Macports requires no binaries to be shipped by the project. If we have a maintainer for an OSX package independently of macports it would make sense to ship binary libraries. Until that time I don't think I can help you (I don't even have OSX).

**Comment by mike-lischke** [comment]
I see. Too bad then. I'd write a better (native) GUI client for openconnect if I'd had the libs. But without them a good chance will be lost.

**Comment by nmav** [comment]
Why don't you use the libs compiled by the macports package?

**Comment by mike-lischke** [comment]
Unfortunately, there are no libs. It's just a single binary (static libs, remember?).

**Comment by nmav** [comment]
But if you were able to link with static libs, these should be available somewhere in your system.

**Comment by mike-lischke** [comment]
I can't link, since I don't have the static libs. This enhancement request is exactly about this.

**Comment by nmav** [comment]
If I understand correctly how macports works, it downloads the sources, compiles, links and gives you the executable. In that process it downloads the libraries you wanted, and links with them (statically). So if you build the macports package you already have the openconnect library somewhere.
