### ISSUE TITLE
root privilege enhancement

### ISSUE THREAD

**Issue by wacky6** [openconnect/openconnect-gui#47]
Under Mac OS X, run from launchpad, warns about root privilege.

Improvement: request privilege elevation, prompt an authentication dialog, etc.

Possible solution:
1. set SUID on executable, add `QApplication::setSetuidAllowed(true);` to main.cpp before `QApplication a(argc, argv)`
2. prompt for user authentication

My preference is the first one.

<img width="410" alt="2015-08-31 5 14 36" src="https://cloud.githubusercontent.com/assets/9319556/9575641/c632ff2c-5003-11e5-90e1-50199557df87.png">

> https://forum.qt.io/topic/50628/how-to-use-qcoreapplication-to-set-root-permission-to-my-app/4

**Comment by nmav** [comment]
Hi, As I have no access to a Mac OS X I'd prefer a pull request which has the necessary changes for that feature.

**Comment by wacky6** [comment]
After doing some research:
It appears code-siging and OSX-specific tweaks are needed to allow application to run as root.

These changes are not easy to integrate with Qt, and may cause problems to MS build.

However, SUID fix may be helpful to Linux users, but I can't test it because I don't have a working linux at hand.

User@SHA ref: wacky6@50d4f86e6f89df9c78a8f14148c577da792fcb1f

**Comment by nmav** [comment]
We can always put MacOSX specific code in an "#if defined(APPLE) && defined(TARGET_OS_MAC)" section. We do that for several windows-only features. If you have an improvement for this platform I'll be happy to include it.
