### ISSUE TITLE
Bug with vmware bridge network.

### ISSUE THREAD

**Issue by kxmp** [openconnect/openconnect-gui#50]
If I run a ocserv server on vmware bridged network, openconnect will add a wrong route table that makes connect fail.
My local ip is 192.168.1.2 and 192.168.1.4(server ip) is bridged to 192.168.1.2.
When openconnect finished auth, It add a wrong route table 192.168.1.4 via gateway 192.168.1.1 and interfaces is 192.168.1.2 and it makes 192.168.1.4 unaccessable!
I think there is no need to add that table.
![2015-09-08_001503](https://cloud.githubusercontent.com/assets/6483602/9720218/bb5819c8-55be-11e5-98c7-a42e991ffb83.png)

**Comment by nmav** [comment]
That setup seems quite strange. If your local IP is the same as the LAN of the server, your setup will have problems. You should have different networks on server and client prior to connection.

**Comment by nmav** [comment]
Since there is no reply I assume it is a local setup issue. Feel free to reopen the bug if it is another issue.
