### ISSUE TITLE
Silent, unattender install

### ISSUE THREAD

**Issue by samupl** [openconnect/openconnect-gui#51]
Hello!

Openconnect seems to be able to be installed without any attention using the /S switch for the installer, but an annoying TAP installation window still pops up. 

There should be a switch to ommit the TAP installation, or at least also make it silent. 

In my setup, I also get TAP from OpenVPN so there is no need to install it again, but an option to install it without any attention would also be great.

**Comment by horar** [comment]
Actual build CMake scripts generate a installer that is allow to install silently everything (incl. vcredist and tap drivers), except we want re-install the app the we will be asked if we wish to uninstall previous installation.
On other side, the standard installation allow to select what will be installed aka app, tap drivers, vcredist drivers... 

If you feel this may be more user-interactive, please drop a ticket. But this will require to add custom nsis installer script (or we can look to other installer type e.g. WIX).
