### ISSUE TITLE
Is there a plan to make openconnect-gui available for Linux (X)

### ISSUE THREAD

**Issue by Kalle72** [openconnect/openconnect-gui#52]
Hi,

is there a plan to make openconnect-gui available for Linux (X)? I am asking because for any Linux user who does not use the "nm-applet" this would be extremely nice. The Mac OsX version lets me hope ;-)

Cheers!
Kalle

**Comment by nmav** [comment]
Hi,
 It should compile on Linux out of the box (I actually test it there). Most likely you only need to fix the vpnc-script location.

**Comment by Kalle72** [comment]
Thanks for the reply. I am on gentoo so compiling should not be a problem. However, do you have some hints how to do. ;-)

**Comment by nmav** [comment]
I believe it should be something along the lines qmake && make. You'll need to have install gnutls-dev and libopenconnect-dev.
