### ISSUE TITLE
Building for OSX

### ISSUE THREAD

**Issue by mjn1210** [openconnect/openconnect-gui#53]
All, complete newbie here,but trying to install the Mac OSX port with MacPorts, but I am getting the following error:

cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_net_openconnect-gui/openconnect-gui/work/openconnect-gui-1.3" && /usr/bin/make -j8 -w all
make: Entering directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_net_openconnect-gui/openconnect-gui/work/openconnect-gui-1.3'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/opt/local/libexec/qt5-mac/lib -o openconnect-gui.app/Contents/MacOS/openconnect-gui main.o mainwindow.o vpninfo.o storage.o editdialog.o keypair.o key.o cert.o logdialog.o gtdb.o cryptdata.o qrc_resources.o moc_mainwindow.o moc_editdialog.o moc_logdialog.o   -F/opt/local/libexec/qt5-mac/lib -L/usr/local/lib -lopenconnect -lgnutls -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtNetwork -framework OpenGL -framework AGL 
Undefined symbols for architecture x86_64:
  "_gnutls_x509_crt_import_pkcs11_url", referenced from:
      Cert::import_file(QString&) in cert.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [openconnect-gui.app/Contents/MacOS/openconnect-gui] Error 1
make: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_net_openconnect-gui/openconnect-gui/work/openconnect-gui-1.3'

Any assistance would be appreciated.

**Comment by nmav** [comment]
No idea about macports. I'd suggest to contact the macports package author directly, or refer him here.
