### ISSUE TITLE
Error setting up DTLS

### ISSUE THREAD

**Issue by nmcye** [openconnect/openconnect-gui#54]
openconnect 1.3 running on Windows 7 SP1 64bit.
Connecting to Cisco ASA 5505
Cisco Adaptive Security Appliance Software Version 9.2(4)
Device Manager Version 7.5(1)

I manage to connect to the VPN using openconnect, and can successfully browse the internet, but DTLS does not work.

Log is here:
http://fpaste.org/271282/31418481/

**Comment by nmav** [comment]
According to the log your server doesn't support DTLS.

**Comment by nmcye** [comment]
Problem was on my side.

For reference:

On the Cisco ASA 5505, in SSL Settings, only the following algorithms were active:

DHE-AES256-SHA1
DHE-AES128-SHA1

It needed to be changed to the following in order to enable DTLS:

DHE-AES256-SHA1
DHE-AES128-SHA1
AES256-SHA1
AES128-SHA1
