### ISSUE TITLE
In some systems the output from the vpnc-script is not displayed in log

### ISSUE THREAD

**Issue by spetragl** [openconnect/openconnect-gui#59]
It would be nice if the log function could append the cscript output of vpnc-script-win.js to the log Window so we can catch any errors. If would also be nice if the button was labeled.
Thanks

The log is saved in a temporary file within the home directory. If it cannot be opened you'll see a log entry with the reason, please copy paste that here (feel free to re-open the bug if it is still there).

I checked and no such file appears in C:\Program Files (x86)\OpenConnect.
However a file openconnect-gui.XXXXXX in %TEMP% does appear with 0 bytes.

A message is displayed saying vpnc.log not found.
If I pre-allocate the file in %TEMP%, the message goes away, but still no Cscript output.

**Comment by spetragl** [comment]
I upgraded to v1.3 and the message "vpnc.log not found" still appears when I disconnect.

**Comment by spetragl** [comment]
the 2>&1 seems to fix  the missing command output in the GUI log (except for Disconnect; not sure why only that is missing).

**Comment by horar** [comment]
Improved vpnc script output redirection is done in in merge request #110

Actually, we don't have file-based logging. The log is in memory only in string list.
This may change with implementation of #111

**Comment by spetragl** [comment]
Any idea when the next compiled version (.exe) for Windows will be released?
  ----- Original Message -----

**Comment by horar** [comment]
@spetragl hi, yes, stay tuned... I plan make a RC package in next weeks (definitely in June), there are many changes and some issues may be meantime solved and we will see what ticket can be closed and what are still open
