### ISSUE TITLE
Suggestions for UI Improvements #1 - Control Over GUI Minimize

### ISSUE THREAD

**Issue by TheAndyMac** [openconnect/openconnect-gui#60]
Adding to a set of suggestions (which I am keeping separate so that you can track each separately) and adding to the comment about getting left and right click behaviours on the notification area icon....

It would be good to get minimize / minimize to notification area / close options consistent and configurable. Maybe two UI options should be available for the UI to either "Close to Notification Area" or "Exit on Close, with prompt if still connected" and to either "Minimize to Taskbar" or "Minimize to Notification Area".

**Comment by nmav** [comment]
Noted. I'll consider them in the next release. Note however, that a pull request would greatly help and increase the chances of it being included.
