### ISSUE TITLE
Suggestions for UI Improvements #2 - Notification Area Icon and Context Menu

### ISSUE THREAD

**Issue by TheAndyMac** [openconnect/openconnect-gui#61]
It would be really good to have the icon in the taskbar notification area (and maybe even the taskbar) to show the status of the connection - maybe a coloured background or similar?

It would also be great to have some right-click context menu options on the notification area icon, such as Open [default operation], Disconnect (when connected), View Log, Options, and maybe even Connect (when not) with click/double click still opening the app.

**Comment by horar** [comment]
Paragraph 2 should be more-less done and with about first one paragraph - in present we already have different icons for disconnected/connected state.
Yes, it may be improved and we can add "animated" icon fot ongoing connection status indication etc. 
This is my plan in near time to update connection indication and moreover I would like look closer to connection progress if we can indicate on win8-10 the progress via taskbar icon....
