### ISSUE TITLE
UX design comments for startup screen

### ISSUE THREAD

**Issue by nmav** [openconnect/openconnect-gui#73]
Some comments received by Lenka Horakova (lhorakov@redhat.com):

* Startup screen: Move about to options and add label over server address so that's clear what is it about.

* Startup screen: Simplify interface by making connect and disconnect a single button that changes action depending on current status (connected/disconnected).

* Startup screen: Replace semaphore with something that is more relevant to VPN.

* Main screen log line: When no message is displayed and status is connected it may be better to print "Connected to XXX", where XXX the server name, so that the user will know where he's connected to even when changing the server field (e.g., to edit another server).

**Comment by horar** [comment]
My note to 4: I think, it would be better to keep it as is. The status bar is updated with status messages in connected state and meantime, I disabled editing/deleting profile in connected state (I plan to change edit/delete flow little bit more).
If someone wish to have this, pls. come back...
