### ISSUE TITLE
GUI doesn't act on dead connection

### ISSUE THREAD

**Issue by nielspeen** [openconnect/openconnect-gui#9]
After waking up my laptop the log shows that the OpenConnect connection died:

2014-09-09 09:17 DTLS Dead Peer Detection detected dead peer!
2014-09-09 09:17 CSTP Dead Peer Detection detected dead peer!

But it doesn't take any action. (Does not revert to disconnect state, does not re-connect, does not show an error.)

**Comment by nmav** [comment]
Is that issue still occurring? I'm unable to reproduce in windows 7.

**Comment by nielspeen** [comment]
I've not experienced this with the more recent versions.

**Comment by janssen** [comment]
I'm seeing this on Ubuntu 15.04, openconnect 6.00.

**Comment by nmav** [comment]
@janssen that's unrelated to openconnect gui. Most likely you are using networkmanager.
