### ISSUE TITLE
Bind to specific interface

### ISSUE THREAD

**Issue by brunis** [openconnect/openconnect-gui#90]
Hi,

I'm stuck on an isp that has problems with letting throug VPN connections, i can connect to the destination network but all traffic is blocked somehow. So i bought a USB modem for Mobile data and it's working great with the VPN connection. But i would prefer to only my route my vpn data through the Mobile data and stay connected to my WIFI for all other traffic.

Is it possible to make the TAP-Windows Adapter only route data through a specific interface in my system?

regards,
Brunis

**Comment by nmav** [comment]
No idea about the adapter, but would disabling UDP in the client work?

**Comment by brunis** [comment]
You ...  you deserve a medal! Thank you!!

I'm assuming it could also be handled with some routing, but i'm not proficient enough in networking to handle that.
