### ISSUE TITLE
After successful connection, if I touch the start bar icon, it quietly terminates.

### ISSUE THREAD

**Issue by spetragl** [openconnect/openconnect-gui#92]
I've been running v0.9 flawlessly on W7. 
I upgraded to v1.3 and am having an issue associated with the log window.

a. Start openconnect (it wasn't running).
b. Open a log window; don't touch it.
c. I enter my password, it completes the handshake and minimizes.
d. Close the log window.
e. Now if I touch the icon in the "start bar", 
    openconnect quietly terminates without a message.

There's nothing in the Event Viewer.
It does seem to run the script "disconnect" however.

BTW If I connect first, then open the log later, it's OK.

**Comment by horar** [comment]
Hi @spetragl , thanks for report. This issue was already fixed in #78 and will be released with v1.4
