### ISSUE TITLE
Need to check for previous version before re-installing

### ISSUE THREAD

**Issue by spetragl** [openconnect/openconnect-gui#93]
Can the openconnect installer check for a previous version of TAP installed?
If I forget to uninstall and attempt to install, I get weird connection errors on the TAP.

**Comment by horar** [comment]
Hi, thanks for suggestion. I changed already the installer slightly and now it allow us to configure what should be installed (app, tap drivers etc.). Creating more complex installe may be fine, but it's low-prio task for me at this time.
