### ISSUE TITLE
Can't ignore invalid certificates

### ISSUE THREAD

**Issue by SuperJMN** [openconnect/openconnect-gui#95]
I have a server that has an invalid certificate. I have to ignore it and continue with the connection. I don't see the option to do that.

**Comment by horar** [comment]
Hi @SuperJMN , could you please tel me more what you mean with invalid certificate - unsigned, or some weakness? Thanks.
(or may be just put drop here link to your site, to see that error if possible)

**Comment by horar** [comment]
It's not clean for me what is expected in this scenario and there is no update in last 6 months.
