### ISSUE TITLE
Single instance checking

### ISSUE THREAD

**Issue by afl1** [openconnect/openconnect-gui#99]
Please, implement signle instance checking for openconnect-gui. Instead of running second instance activate already running gui.

**Comment by nmav** [comment]
I don't know if that's now possible, but a second instance of openconnect would be the only way to connect to two servers at the same time.

**Comment by horar** [comment]
yeap, I don't want hardcode it into app.
I plan add option into "settings" dialog so if some wish to have only one instance, this feature may be enabled/disabled as needed.
Sometimes the icon in task-bar is hidden by default and user starts the app again. With enabled one-instance approach we just unhide/raise existing instance

**Comment by afl1** [comment]
Why option? You cannot run more than one openconnect VPN. The attempt to establish second VPN  always fails on "Error setting up the TUN device".

**Comment by nielspeen** [comment]
> On Mar 15, 2016, at 23:20, afl1 <notifications@github.com> wrote:
> 
> Why option? You cannot run more than one openconnect VPN. The attempt to establish second VPN always fails on "Error setting up the TUN device”.
> 

That can probably be fixed, and there are some use-cases where multiple tunnels are useful.

In any case, I would strongly prefer if the “one instance” option is enabled by default - it will be what most users expect.

Regards,
Niels

**Comment by horar** [comment]
I don't use multiple openconnect tunnels together (no need), anyway just started 2 different VPN sessions in parallel on MacOS and no error reported; if u have observed any issues, feel free to drop ticket with details (both profile descriptions, both logs etc.)

**Comment by MartinOehler** [comment]
Hello Horar, means "ready" we will get the feature with the next release? 

I also have users that keep klicking on the desktop icon, start multiple instances of the GUI leading to all sorts of unexpected behaviours and would love to have the option within settings.

Thanks in advance for your answer,
Martin
